<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Bongkar_log extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bongkar_log_model');
        $this->load->model('Rekap_total');
        
    }

    /*
     * Listing of bongkar_log
     */
    function index()
    {
        $data['bongkar_log'] = $this->Bongkar_log_model->get_all_bongkar_log($this->session->userdata('no_bpk'));

        $data['bongkar_log_total'] = $this->Bongkar_log_model        ->get_total_bongkar_log($this->session->userdata('no_bpk'));

        $data['_view'] = 'bongkar_log/index';
        $this->load->view('layouts/main',$data);

    }

    /*
     * Adding a new bongkar_log
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('grade','Grade','required|integer');
		$this->form_validation->set_rules('a_rot','A Rot','integer');
		$this->form_validation->set_rules('a_band1','A Band1','integer');
		$this->form_validation->set_rules('a_band2','A Band2','integer');
		$this->form_validation->set_rules('a_band3','A Band3','integer');
		$this->form_validation->set_rules('b_rot','B Rot','integer');
		$this->form_validation->set_rules('b_band1','B Band1','integer');
		$this->form_validation->set_rules('b_band2','B Band2','integer');
		$this->form_validation->set_rules('b_band3','B Band3','integer');
		$this->form_validation->set_rules('satum_rot','Satum Rot','integer');
		$this->form_validation->set_rules('satum_band1','Satum Band1','integer');
		$this->form_validation->set_rules('satum_band2','Satum Band2','integer');
		$this->form_validation->set_rules('satum_band3','Satum Band3','integer');
		$this->form_validation->set_rules('afkir_rot','Afkir Rot','integer');
		$this->form_validation->set_rules('afkir_band1','Afkir Band1','integer');
		$this->form_validation->set_rules('afkir_band2','Afkir Band2','integer');
		$this->form_validation->set_rules('afkir_band3','Afkir Band3','integer');
		$this->form_validation->set_rules('bpk_no_bpk','Bpk No Bpk','required|max_length[10]');

		if($this->form_validation->run())
        {
            $params = array(
				'grade' => $this->input->post('grade'),
				'a_rot' => $this->input->post('a_rot'),
				'a_band1' => $this->input->post('a_band1'),
				'a_band2' => $this->input->post('a_band2'),
				'a_band3' => $this->input->post('a_band3'),
				'b_rot' => $this->input->post('b_rot'),
				'b_band1' => $this->input->post('b_band1'),
				'b_band2' => $this->input->post('b_band2'),
				'b_band3' => $this->input->post('b_band3'),
				'satum_rot' => $this->input->post('satum_rot'),
				'satum_band1' => $this->input->post('satum_band1'),
				'satum_band2' => $this->input->post('satum_band2'),
				'satum_band3' => $this->input->post('satum_band3'),
				'afkir_rot' => $this->input->post('afkir_rot'),
				'afkir_band1' => $this->input->post('afkir_band1'),
				'afkir_band2' => $this->input->post('afkir_band2'),
				'afkir_band3' => $this->input->post('afkir_band3'),
				'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
            );

            $bongkar_log_id = $this->Bongkar_log_model->add_bongkar_log($params);
            redirect('bongkar_log/index');
        }
        else
        {
            $data['_view'] = 'bongkar_log/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a bongkar_log
     */
    function edit($id)
    {
        // check if the bongkar_log exists before trying to edit it
        $data['bongkar_log'] = $this->Bongkar_log_model->get_bongkar_log($id);

        if(isset($data['bongkar_log']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('grade','Grade','required|integer');
			$this->form_validation->set_rules('a_rot','A Rot','integer');
			$this->form_validation->set_rules('a_band1','A Band1','integer');
			$this->form_validation->set_rules('a_band2','A Band2','integer');
			$this->form_validation->set_rules('a_band3','A Band3','integer');
			$this->form_validation->set_rules('b_rot','B Rot','integer');
			$this->form_validation->set_rules('b_band1','B Band1','integer');
			$this->form_validation->set_rules('b_band2','B Band2','integer');
			$this->form_validation->set_rules('b_band3','B Band3','integer');
			$this->form_validation->set_rules('satum_rot','Satum Rot','integer');
			$this->form_validation->set_rules('satum_band1','Satum Band1','integer');
			$this->form_validation->set_rules('satum_band2','Satum Band2','integer');
			$this->form_validation->set_rules('satum_band3','Satum Band3','integer');
			$this->form_validation->set_rules('afkir_rot','Afkir Rot','integer');
			$this->form_validation->set_rules('afkir_band1','Afkir Band1','integer');
			$this->form_validation->set_rules('afkir_band2','Afkir Band2','integer');
			$this->form_validation->set_rules('afkir_band3','Afkir Band3','integer');
			$this->form_validation->set_rules('bpk_no_bpk','Bpk No Bpk','required|max_length[10]');

			if($this->form_validation->run())
            {
                $params = array(
					'grade' => $this->input->post('grade'),
					'a_rot' => $this->input->post('a_rot'),
					'a_band1' => $this->input->post('a_band1'),
					'a_band2' => $this->input->post('a_band2'),
					'a_band3' => $this->input->post('a_band3'),
					'b_rot' => $this->input->post('b_rot'),
					'b_band1' => $this->input->post('b_band1'),
					'b_band2' => $this->input->post('b_band2'),
					'b_band3' => $this->input->post('b_band3'),
					'satum_rot' => $this->input->post('satum_rot'),
					'satum_band1' => $this->input->post('satum_band1'),
					'satum_band2' => $this->input->post('satum_band2'),
					'satum_band3' => $this->input->post('satum_band3'),
					'afkir_rot' => $this->input->post('afkir_rot'),
					'afkir_band1' => $this->input->post('afkir_band1'),
					'afkir_band2' => $this->input->post('afkir_band2'),
					'afkir_band3' => $this->input->post('afkir_band3'),
					'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
                );

                $this->Bongkar_log_model->update_bongkar_log($id,$params);
                redirect('bongkar_log/index');
            }
            else
            {
                $data['_view'] = 'bongkar_log/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bongkar_log you are trying to edit does not exist.');
    }

    /*
     * Deleting bongkar_log
     */
    function remove($id)
    {
        $bongkar_log = $this->Bongkar_log_model->get_bongkar_log($id);

        // check if the bongkar_log exists before trying to delete it
        if(isset($bongkar_log['id']))
        {
            $this->Bongkar_log_model->delete_bongkar_log($id);
            redirect('bongkar_log/index');
        }
        else
            show_error('The bongkar_log you are trying to delete does not exist.');
    }

}
