<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Grade extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Grade_model');
    }

    /*
     * Listing of grade
     */
    function index()
    {
      $data['grade'] = $this->Grade_model->get_all_grade();

        $data['_view'] = 'grade/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new grade
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {
            $params = array(
              'grade' => $this->input->post('grade')
            );

            $grade_id = $this->Grade_model->add_grade($params);
            redirect('grade/index');
        }
        else
        {
            $data['_view'] = 'grade/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a grade
     */
    function edit($grade)
    {
        // check if the grade exists before trying to edit it
        $data['grade'] = $this->Grade_model->get_grade($grade);

        if(isset($data['grade']['grade']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {
                $params = array(
                );

                $this->Grade_model->update_grade($grade,$params);
                redirect('grade/index');
            }
            else
            {
                $data['_view'] = 'grade/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The grade you are trying to edit does not exist.');
    }

    /*
     * Deleting grade
     */
    function remove($grade)
    {
        $grade = $this->Grade_model->get_grade($grade);

        // check if the grade exists before trying to delete it
        if(isset($grade['grade']))
        {
            $this->Grade_model->delete_grade($grade);
            redirect('grade/index');
        }
        else
            show_error('The grade you are trying to delete does not exist.');
    }

}
