<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Harga_m3 extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Harga_m3_model');
        $this->load->model('Rekap_total');
    }

    /*
     * Listing of harga_m3
     */
    function index()
    {
        $data['harga_m3'] = $this->Harga_m3_model->get_all_harga_m3();

        $data['_view'] = 'harga_m3/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new harga_m3
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('grade_grade','Grade Grade','max_length[5]');

		if($this->form_validation->run())
        {
            $params = array(
				'grade_grade' => $this->input->post('grade_grade'),
				'harga' => $this->input->post('harga'),
            );

            $harga_m3_id = $this->Harga_m3_model->add_harga_m3($params);
            redirect('harga_m3/index');
        }
        else
        {
            $data['_view'] = 'harga_m3/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a harga_m3
     */
    function edit($id)
    {
        // check if the harga_m3 exists before trying to edit it
        $data['harga_m3'] = $this->Harga_m3_model->get_harga_m3($id);

        if(isset($data['harga_m3']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('grade_grade','Grade Grade','max_length[5]');

			if($this->form_validation->run())
            {
                $params = array(
					'grade_grade' => $this->input->post('grade_grade'),
					'harga' => $this->input->post('harga'),
                );

                $this->Harga_m3_model->update_harga_m3($id,$params);
                redirect('harga_m3/index');
            }
            else
            {
                $data['_view'] = 'harga_m3/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The harga_m3 you are trying to edit does not exist.');
    }

    /*
     * Deleting harga_m3
     */
    function remove($id)
    {
        $harga_m3 = $this->Harga_m3_model->get_harga_m3($id);

        // check if the harga_m3 exists before trying to delete it
        if(isset($harga_m3['id']))
        {
            $this->Harga_m3_model->delete_harga_m3($id);
            redirect('harga_m3/index');
        }
        else
            show_error('The harga_m3 you are trying to delete does not exist.');
    }

}
