<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Rekap_pembayaran_log extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rekap_total');
        $this->load->model('Rekap_pembayaran_log_model');
    }

    /*
     * Listing of rekap_pembayaran_log
     */
    function index()
    {
        // echo $this->session->userdata('grade');
        $data['rekap_pembayaran_log'] = $this->Rekap_pembayaran_log_model->get_rekap_pembayaran_log($this->session->userdata('no_bpk'));
        $data['_view'] = 'rekap_pembayaran_log/index';
        $this->load->view('layouts/main',$data);
    }



    /*
     * Adding a new rekap_pembayaran_log
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('grade','Grade','required|integer');
		$this->form_validation->set_rules('a_pc','A Pc','integer');
		$this->form_validation->set_rules('b_pc','B Pc','integer');
		$this->form_validation->set_rules('satum_pc','Satum Pc','integer');
		$this->form_validation->set_rules('afkir_pc','Afkir Pc','integer');

		if($this->form_validation->run())
        {
            $params = array(
				'grade' => $this->input->post('grade'),
				'a_pc' => $this->input->post('a_pc'),
				'a_m3' => $this->input->post('a_m3'),
				'b_pc' => $this->input->post('b_pc'),
				'b_m3' => $this->input->post('b_m3'),
				'satum_pc' => $this->input->post('satum_pc'),
				'satum_m3' => $this->input->post('satum_m3'),
				'afkir_pc' => $this->input->post('afkir_pc'),
				'afkir_m3' => $this->input->post('afkir_m3'),
				'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
            );
            $rekap_pembayaran_log_id = $this->Rekap_pembayaran_log_model->add_rekap_pembayaran_log($params);
            redirect('rekap_pembayaran_log/index');
        }
        else
        {
            $data['_view'] = 'rekap_pembayaran_log/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a rekap_pembayaran_log
     */
    function edit($id)
    {
        // check if the rekap_pembayaran_log exists before trying to edit it
        $data['rekap_pembayaran_log'] = $this->Rekap_pembayaran_log_model->get_rekap_pembayaran_log($id);

        if(isset($data['rekap_pembayaran_log']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('grade','Grade','required|integer');
			$this->form_validation->set_rules('a_pc','A Pc','integer');
			$this->form_validation->set_rules('b_pc','B Pc','integer');
			$this->form_validation->set_rules('satum_pc','Satum Pc','integer');
			$this->form_validation->set_rules('afkir_pc','Afkir Pc','integer');

			if($this->form_validation->run())
            {
                $params = array(
					'grade' => $this->input->post('grade'),
					'a_pc' => $this->input->post('a_pc'),
					'a_m3' => $this->input->post('a_m3'),
					'b_pc' => $this->input->post('b_pc'),
					'b_m3' => $this->input->post('b_m3'),
					'satum_pc' => $this->input->post('satum_pc'),
					'satum_m3' => $this->input->post('satum_m3'),
					'afkir_pc' => $this->input->post('afkir_pc'),
					'afkir_m3' => $this->input->post('afkir_m3'),
					'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
                );

                $this->Rekap_pembayaran_log_model->update_rekap_pembayaran_log($id,$params);
                redirect('rekap_pembayaran_log/index');
            }
            else
            {
                $data['_view'] = 'rekap_pembayaran_log/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The rekap_pembayaran_log you are trying to edit does not exist.');
    }

    /*
     * Deleting rekap_pembayaran_log
     */
    function remove($id)
    {
        $rekap_pembayaran_log = $this->Rekap_pembayaran_log_model->get_rekap_pembayaran_log($id);

        // check if the rekap_pembayaran_log exists before trying to delete it
        if(isset($rekap_pembayaran_log['id']))
        {
            $this->Rekap_pembayaran_log_model->delete_rekap_pembayaran_log($id);
            redirect('rekap_pembayaran_log/index');
        }
        else
            show_error('The rekap_pembayaran_log you are trying to delete does not exist.');
    }

}
