<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Rekap_stok_akhir extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bpk_model');
        $this->load->model('Rekap_pembayaran_log_model');
        $this->load->model('Bongkar_log_model');
        $this->load->model('Rekap_total');
    }

    /*
     * Listing of serah_terima_log
     */
    function index()
    {
      $data['bpk'] = $this->Bpk_model->jumlah_bpk();
      $data['pemakaian'] = $this->Bongkar_log_model->get_pemakaian_log();
      $data['total_pemakaian'] = $this->Bongkar_log_model->get_total_pemakaian();
      $data['persediaan'] = $this->Rekap_pembayaran_log_model->get_persediaan_log();
      $data['total_persediaan'] = $this->Rekap_pembayaran_log_model->get_total_persediaan();

        $data['_view'] = 'rekap_stok_akhir/index';
        $this->load->view('layouts/main',$data);
    }

    function cetak()
    {
      $bulan = $this->input->post('bulan');
      $tahun = $this->input->post('tahun');
      $tanggal = $tahun.'-'.$bulan;
      $data['bpk'] = $this->Bpk_model->jumlah_bpk_skr($tanggal);
      $data['tanggal'] = $tanggal;
      $data['pemakaian_skr'] = $this->Bongkar_log_model->pemakaian_skr($tanggal);
      $data['total_pemakaian_skr'] = $this->Bongkar_log_model->get_total_pemakaian();
      $data['persediaan_skr'] = $this->Rekap_pembayaran_log_model->persediaan_skr($tanggal);
      $data['total_persediaan_skr'] = $this->Rekap_pembayaran_log_model->get_total_persediaan();

        $this->load->view('rekap_stok_akhir/cetak',$data);
    }

}
