<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Rekap_per_bpk extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bpk_model');
        $this->load->model('Rekap_pembayaran_log_model');
        $this->load->model('Bongkar_log_model');
        $this->load->model('Rekap_total');
    }

    /*
     * Listing of serah_terima_log
     */
    function index()
    {
      $data['bpk'] = $this->Bpk_model->jumlah_bpk();
      $data['pemakaian'] = $this->Bongkar_log_model->get_pemakaian_log();
      $data['total_pemakaian'] = $this->Bongkar_log_model->get_total_pemakaian();
      $data['persediaan'] = $this->Rekap_pembayaran_log_model->get_persediaan_log();
      $data['total_persediaan'] = $this->Rekap_pembayaran_log_model->get_total_persediaan();

        $data['_view'] = 'rekap_per_bpk/index';
        $this->load->view('layouts/main',$data);
    }

    function cetak()
    {
      $data['bpk'] = $this->Bpk_model->jumlah_bpk();
      $data['pemakaian_skr'] = $this->Bongkar_log_model->get_pemakaian_log();
      $data['total_pemakaian_skr'] = $this->Bongkar_log_model->get_total_pemakaian();
      $data['persediaan_skr'] = $this->Rekap_pembayaran_log_model->get_persediaan_log();
      $data['total_persediaan_skr'] = $this->Rekap_pembayaran_log_model->get_total_persediaan();
      // $data['pemakaian_skr'] = $this->Bongkar_log_model->pemakaian_skr(date("Y-m"));
      // $data['total_pemakaian_skr'] = $this->Bongkar_log_model->get_total_pemakaian(date("Y-m"));
      // $data['persediaan_skr'] = $this->Rekap_pembayaran_log_model->persediaan__skr(date("Y-m"));
      // $data['total_persediaan_skr'] = $this->Rekap_pembayaran_log_model->get_total_persediaan(date("Y-m"));

      // $data['_view'] = 'rekap_per_bpk/index';
      $this->load->view('rekap_per_bpk/cetak',$data);
    }



}
