<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Rekap_penerimaan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bpk_model');
        $this->load->model('Rekap_total');
        $this->load->model('Rekap_pembayaran_log_model');
    }

    /*
     * Listing of serah_terima_log
     */
    function index()
    {
      $data['bpk'] = $this->Bpk_model->jumlah_bpk();
      $data['persediaan'] = $this->Rekap_pembayaran_log_model->get_persediaan_log();
      $data['total_persediaan'] = $this->Rekap_pembayaran_log_model->get_total_persediaan();

        $data['_view'] = 'rekap_penerimaan/index';
        $this->load->view('layouts/main',$data);
    }



}
