<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Rekap_pemakaian extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bpk_model');
        $this->load->model('Rekap_total');
        $this->load->model('Bongkar_log_model');
    }

    /*
     * Listing of serah_terima_log
     */
    function index()
    {
      $data['bpk'] = $this->Bpk_model->jumlah_bpk();
      $data['pemakaian'] = $this->Bongkar_log_model->get_pemakaian_log();
      $data['total_pemakaian'] = $this->Bongkar_log_model->get_total_pemakaian();

        $data['_view'] = 'rekap_pemakaian/index';
        $this->load->view('layouts/main',$data);
    }



}
