<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Selisih_stok extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Selisih_stok_model');
    } 

    /*
     * Listing of selisih_stok
     */
    function index()
    {
        $data['selisih_stok'] = $this->Selisih_stok_model->get_all_selisih_stok();

        $data['_view'] = 'selisih_stok/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new selisih_stok
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('grade','Grade','required|integer');
		$this->form_validation->set_rules('a','A','integer');
		$this->form_validation->set_rules('b','B','integer');
		$this->form_validation->set_rules('satum','Satum','integer');
		$this->form_validation->set_rules('afkir','Afkir','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'grade' => $this->input->post('grade'),
				'a' => $this->input->post('a'),
				'b' => $this->input->post('b'),
				'satum' => $this->input->post('satum'),
				'afkir' => $this->input->post('afkir'),
				'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
            );
            
            $selisih_stok_id = $this->Selisih_stok_model->add_selisih_stok($params);
            redirect('selisih_stok/index');
        }
        else
        {            
            $data['_view'] = 'selisih_stok/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a selisih_stok
     */
    function edit($id)
    {   
        // check if the selisih_stok exists before trying to edit it
        $data['selisih_stok'] = $this->Selisih_stok_model->get_selisih_stok($id);
        
        if(isset($data['selisih_stok']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('grade','Grade','required|integer');
			$this->form_validation->set_rules('a','A','integer');
			$this->form_validation->set_rules('b','B','integer');
			$this->form_validation->set_rules('satum','Satum','integer');
			$this->form_validation->set_rules('afkir','Afkir','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'grade' => $this->input->post('grade'),
					'a' => $this->input->post('a'),
					'b' => $this->input->post('b'),
					'satum' => $this->input->post('satum'),
					'afkir' => $this->input->post('afkir'),
					'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
                );

                $this->Selisih_stok_model->update_selisih_stok($id,$params);            
                redirect('selisih_stok/index');
            }
            else
            {
                $data['_view'] = 'selisih_stok/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The selisih_stok you are trying to edit does not exist.');
    } 

    /*
     * Deleting selisih_stok
     */
    function remove($id)
    {
        $selisih_stok = $this->Selisih_stok_model->get_selisih_stok($id);

        // check if the selisih_stok exists before trying to delete it
        if(isset($selisih_stok['id']))
        {
            $this->Selisih_stok_model->delete_selisih_stok($id);
            redirect('selisih_stok/index');
        }
        else
            show_error('The selisih_stok you are trying to delete does not exist.');
    }
    
}
