<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
if ( ! defined('BASEPATH')) exit('No direct script access allowed');
class Serah_terima_log extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bpk_model');
        $this->load->model('Serah_terima_log_model');
        $this->load->model('Rekap_pembayaran_log_model');
        $this->load->model('Rekap_total');
        $this->load->model('Cek_log_model');
        $this->load->model('Selisih_stok_model');
        $this->load->model('mread');
        $this->load->library(array('PHPExcel','PHPExcel/IOFactory'));
        $this->load->library('CFPDF');
    }

    /*
     * Listing of serah_terima_log
     */
    public function index()
    {
        $data['bpk'] = $this->Bpk_model->get_bpk($this->session->userdata('no_bpk'));
        $data['serah_terima_log'] = $this->Serah_terima_log_model->get_all_serah_terima_log($this->session->userdata('no_bpk'));

        $data['rekap_pembayaran_log'] = $this->Rekap_pembayaran_log_model->get_rekap_pembayaran_log($this->session->userdata('no_bpk'));

        $data['rekap_total_log'] = $this->Rekap_pembayaran_log_model->get_total_rekap_pembayaran_log($this->session->userdata('no_bpk'));

        $data['_view'] = 'serah_terima_log/index';
        $this->load->view('layouts/main',$data);
    }

    public function cetak_rekap_log($no_bpk)
    {

        $data['bpk'] = $this->Bpk_model->get_bpk($no_bpk);

        if($data['bpk']['jenis_kayu']=="Sengon"){

          $data['serah_terima_log'] = $this->Serah_terima_log_model->get_all_serah_terima_log($this->session->userdata('no_bpk'));

          $data['rekap_pembayaran_log'] = $this->Rekap_pembayaran_log_model->get_rekap_pembayaran_log($this->session->userdata('no_bpk'));
          $data['harga_m3'] = $this->Rekap_pembayaran_log_model->get_harga_m3();

          foreach ($data['harga_m3'] as $h) {
                $harga[] = $h['harga'];
          }

          $ar = $this->Rekap_total->get_ar($this->session->userdata('no_bpk'));
          $a0 = $this->Rekap_total->get_a0($this->session->userdata('no_bpk'));
          $a1 = $this->Rekap_total->get_a1($this->session->userdata('no_bpk'));
          $a21 = $this->Rekap_total->get_a21($this->session->userdata('no_bpk'));
          $a22 = $this->Rekap_total->get_a22($this->session->userdata('no_bpk'));
          $a3 = $this->Rekap_total->get_a3($this->session->userdata('no_bpk'));
          $a4 = $this->Rekap_total->get_a4($this->session->userdata('no_bpk'));

          $total_afkir_m3 = $a0['j_afkir_m3']+$a1['j_afkir_m3']+$a21['j_afkir_m3']+$a22['j_afkir_m3']+$a3['j_afkir_m3']+$a4['j_afkir_m3']+$ar['j_afkir_m3'];

          $total_b_m3 =  $a0['j_b_m3']+$a1['j_b_m3']+$a21['j_b_m3']+$a22['j_b_m3']+$a3['j_b_m3']+$a4['j_b_m3']+$ar['j_b_m3'];

          $total_b_pc  = $a0['j_b_pc']+$a1['j_b_pc']+$a21['j_b_pc']+$a22['j_b_pc']+$a3['j_b_pc']+$a4['j_b_pc']+$ar['j_b_pc'];

          $total_c_m3 =  $a0['j_c_m3']+$a1['j_c_m3']+$a21['j_c_m3']+$a22['j_c_m3']+$a3['j_c_m3']+$a4['j_c_m3']+$ar['j_c_m3'];

          $total_c_pc  = $a0['j_c_pc']+$a1['j_c_pc']+$a21['j_c_pc']+$a22['j_c_pc']+$a3['j_c_pc']+$a4['j_c_pc']+$ar['j_c_pc'];

          $b_a0 = $harga[7]*$this->Rekap_total->format_angka($a0['j_b_m3']);
          $satum_a0 = $harga[21]*$this->Rekap_total->format_angka($a0['j_satum_m3']);
          $b_satum_a0=$b_a0+$satum_a0;

          $b_a1 = $harga[8]*$this->Rekap_total->format_angka($a1['j_b_m3']);
          $satum_a1 = $harga[22]*$this->Rekap_total->format_angka($a1['j_satum_m3']);
          $b_satum_a1=$b_a1+$satum_a1;

          $b_a21 = $harga[9]*$this->Rekap_total->format_angka($a21['j_b_m3']);
          $satum_a21 = $harga[23]*$this->Rekap_total->format_angka($a21['j_satum_m3']);
          $b_satum_a21=$b_a21+$satum_a21;


          $b_a22 = $harga[10]*$this->Rekap_total->format_angka($a22['j_b_m3']);
          $satum_a22 = $harga[24]*$this->Rekap_total->format_angka($a22['j_satum_m3']);
          $b_satum_a22=$b_a22+$satum_a22;

          $b_a3 = $harga[11]*$this->Rekap_total->format_angka($a3['j_b_m3']);
          $satum_a3 = $harga[25]*$this->Rekap_total->format_angka($a3['j_satum_m3']);
          $b_satum_a3=$b_a3+$satum_a3;

          $b_a4 = $harga[12]*$this->Rekap_total->format_angka($a4['j_b_m3']);
          $satum_a4 = $harga[26]*$this->Rekap_total->format_angka($a4['j_satum_m3']);
          $b_satum_a4=$b_a4+$satum_a4;

          // $total_b_harga  = $b_a0+$b_a1+$b_a21+$b_a22+$b_a3+$b_a4;

          $c_a0 = $harga[14]*$this->Rekap_total->format_angka($a0['j_c_m3']);
          $c_a1 = $harga[15]*$this->Rekap_total->format_angka($a1['j_c_m3']);
          $c_a21 = $harga[16]*$this->Rekap_total->format_angka($a21['j_c_m3']);
          $c_a22 = $harga[17]*$this->Rekap_total->format_angka($a22['j_c_m3']);
          $c_a3 = $harga[18]*$this->Rekap_total->format_angka($a3['j_c_m3']);
          $c_a4 = $harga[19]*$this->Rekap_total->format_angka($a4['j_c_m3']);
          $total_c_harga  = $c_a0+$c_a1+$c_a21+$c_a22+$c_a3+$c_a4;

          $total_afkir_pc = $a0['j_afkir_pc']+$a1['j_afkir_pc']+$a21['j_afkir_pc']+$a22['j_afkir_pc']+$a3['j_afkir_pc']+$a4['j_afkir_pc']+$ar['j_afkir_pc'];

          //$this->load->library('CFPDF');

          $pdf = new FPDF("P","cm","A4");

            $pdf->SetMargins(1,1,1);
            $pdf->AliasNbPages();
            $pdf->AddPage();

            $pdf->SetFont('arial','B',10);
            $pdf->Cell(2.3, 0.8, 'PT. SUMBER ALAM SANTOSO PRATAMA', 0, 0, 'L');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',10);
            $pdf->Cell(11.5, 0.8, 'Dusun Nganjukan RT 05 RW 03', 0, 0, 'L');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1, 0.8, 'NAMA', 0, 0, 'L');
            $pdf->Cell(0.5, 0.8, ':', 0, 0, 'L');
            $pdf->Cell(2.5, 0.8, $data['bpk']['nama_supplier'], 0, 0, 'L');
            $pdf->Cell(1, 0.8, 'NOPOL', 0, 0, 'L');
            $pdf->Cell(0.5, 0.8, ':', 0, 0, 'L');
            $pdf->Cell(2, 0.8, $data['bpk']['no_polisi'], 0, 0, 'L');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',10);
            $pdf->Cell(11.5, 0.8, 'Desa Karangsari Kec. Sempu', 0, 0, 'L');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1, 0.8, 'TGL', 0, 0, 'L');
            $pdf->Cell(0.5, 0.8, ':', 0, 0, 'L');
            $pdf->Cell(2.5, 0.8, $this->Bpk_model->IndonesiaTgl($data['bpk']['tanggal']), 0, 0, 'L');
            $pdf->Cell(1, 0.8, 'KET', 0, 0, 'L');
            $pdf->Cell(0.5, 0.8, ':', 0, 0, 'L');
            $pdf->Cell(2, 0.8, $data['bpk']['jenis_kayu'], 0, 0, 'L');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',10);
            $pdf->Cell(6, 0.8, 'Banyuwangi', 0, 0, 'L');
            $pdf->SetFont('arial','B',10);
            $pdf->Cell(5.5,0.7,'REKAP PEMBAYARAN LOG',0,0,'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1, 0.8, 'BPK', 0, 0, 'L');
            $pdf->Cell(0.5, 0.8, ':', 0, 0, 'L');
            $pdf->Cell(2.5, 0.8, $data['bpk']['no_bpk'], 0, 0, 'L');
            $pdf->Cell(1, 0.8, 'Grader', 0, 0, 'L');
            $pdf->Cell(0.5, 0.8, ':', 0, 0, 'L');
            $pdf->Cell(2.5, 0.8, $data['bpk']['grader'], 0, 0, 'L');

            $pdf->ln(1);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, '1.3 M', 1, 0, 'C');
            $pdf->Cell(0.8, 0.5, 'PCS', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'HARGA/M3', 1, 0, 'C');
            $pdf->Cell(2, 0.5, 'HARGA', 1, 0, 'C');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'B / 1M', 1, 0, 'C');
            $pdf->Cell(0.8, 0.5, 'PCS', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'HARGA/M3', 1, 0, 'C');
            $pdf->Cell(2, 0.5, 'HARGA', 1, 0, 'C');
            $pdf->ln(0.49);
            // $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'RENCEK', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $ar['j_a_pc'], 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $ar['j_a_m3'], 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(2, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'RENCEK', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $ar['j_b_pc']+$ar['j_satum_pc'], 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $ar['j_b_m3']+$ar['j_satum_m3'], 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(2, 0.5, '-', 1, 0, 'R');
            $pdf->ln(0.5);

            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A0 (9-14)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a0['j_a_pc'], 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a0['j_a_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[0]), 1, 0, 'R');
            $a_a0 = $harga[0]*$this->Rekap_total->format_angka($a0['j_a_m3']);
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($a_a0), 1, 0, 'R');
            $pdf->Cell(0.7, 0.8, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A0 (9-14)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a0['j_b_pc']+$a0['j_satum_pc'], 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a0['j_b_m3']+$a0['j_satum_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[14]), 1, 0, 'R');
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($b_satum_a0), 1, 0, 'R');
            $pdf->ln(0.5);

            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A1 (16-18)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a1['j_a_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a1['j_a_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[1]), 1, 0, 'R');
            $a_a1 = $harga[1]*$this->Rekap_total->format_angka($a1['j_a_m3']);
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($a_a1), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A1 (16-18)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a1['j_b_pc']+$a1['j_satum_pc']+0, 1, 0, 'C');
            $j_b_satum_m3 = $a1['j_b_m3']+$a1['j_satum_m3'];
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($j_b_satum_m3), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[8]), 1, 0, 'R');
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($b_satum_a1), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);

            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2.1 (20-24)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a21['j_a_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a21['j_a_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[2]), 1, 0, 'R');
            $a_a21 = $harga[2]*$this->Rekap_total->format_angka($a21['j_a_m3']);
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($a_a21), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2 (20-24)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a21['j_b_pc']+$a21['j_satum_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a21['j_b_m3']+$a21['j_satum_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[9]), 1, 0, 'R');

            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($b_satum_a21), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);

            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2.2 (25-29)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a22['j_a_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a22['j_a_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[3]), 1, 0, 'R');
            $a_a22 = $harga[3]*$this->Rekap_total->format_angka($a22['j_a_m3']);
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($a_a22), 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2.2 (25-29)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a22['j_b_pc']+$a22['j_satum_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a22['j_b_m3']+$a22['j_satum_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[10]), 1, 0, 'R');

            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($b_satum_a22), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);

            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A3 (30-39)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a3['j_a_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a3['j_a_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[4]), 1, 0, 'R');
            $a_a3 = $harga[4]*$this->Rekap_total->format_angka($a3['j_a_m3']);
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($a_a3) , 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'R');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A3 (30-39)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a3['j_b_pc']+$a3['j_satum_pc']+0, 1, 0, 'C');
            $a3_b_m3 = $this->Rekap_total->format_angka($a3['j_b_m3']+$a3['j_satum_m3']);
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a3_b_m3), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[11]), 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($b_satum_a3), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);

            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A4 (40-Up)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a4['j_a_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a4['j_a_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[5]), 1, 0, 'R');

            $a_a4 = $harga[5]*$a4['j_a_m3'];
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($a_a4), 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A4 (40-Up)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a4['j_b_pc']+$a4['j_satum_pc']+0, 1, 0, 'C');
            $a4_b_m3 = $a4['j_b_m3']+$a4['j_satum_m3'];
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a4_b_m3), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[12]), 1, 0, 'R');

            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($b_satum_a4), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);

            $pdf->SetFont('arial','b',9);
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $total_a_pc = $a0['j_a_pc']+$a1['j_a_pc']+$a21['j_a_pc']+$a22['j_a_pc']+$a3['j_a_pc']+$a4['j_a_pc']+$ar['j_a_pc'], 1, 0, 'R');
            $total_a_m3 = $this->Rekap_total->format_angka( $a0['j_a_m3']+$a1['j_a_m3']+$a21['j_a_m3']+$a22['j_a_m3']+$a3['j_a_m3']+$a4['j_a_m3']+$ar['j_a_m3']);
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($total_a_m3) , 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'L');
            $total_a_harga = $a_a0+$a_a1+$a_a21+$a_a22+$a_a3+$a_a4;
            $pdf->SetFont('arial','b',8);
            $pdf->Cell(2, 0.5, 'Rp. '.$this->Rekap_total->format_harga($total_a_harga), 1, 0, 'R');

            $pdf->SetFont('arial','b',9);
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $total_b_satum_pc =$a0['j_b_pc']+$a1['j_b_pc']+$a21['j_b_pc']+$a22['j_b_pc']+$a3['j_b_pc']+$a4['j_b_pc']+$ar['j_b_pc']+ $a0['j_satum_pc']+$a1['j_satum_pc']+$a21['j_satum_pc']+$a22['j_satum_pc']+$a3['j_satum_pc']+$a4['j_satum_pc']+$ar['j_satum_pc'], 1, 0, 'R');
            $total_b_satum_m3 =  $this->Rekap_total->format_angka($a0['j_b_m3']+$a1['j_b_m3']+$a21['j_b_m3']+$a22['j_b_m3']+$a3['j_b_m3']+$a4['j_b_m3']+$ar['j_b_m3']+ $a0['j_satum_m3']+$a1['j_satum_m3']+$a21['j_satum_m3']+$a22['j_satum_m3']+$a3['j_satum_m3']+$a4['j_satum_m3']+$ar['j_satum_m3']);
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($total_b_satum_m3), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'R');
            $total_b_satum_harga = $b_satum_a0+$b_satum_a1+$b_satum_a21+$b_satum_a22+$b_satum_a3+$b_satum_a4;
            $pdf->SetFont('arial','b',8);
            $pdf->Cell(2, 0.5, 'Rp. '.$this->Rekap_total->format_harga($total_b_satum_harga), 1, 0, 'R');
            //garis baru
            $pdf->ln(1.2);


            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'C', 1, 0, 'C');
            $pdf->Cell(0.8, 0.5, 'PCS', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'HARGA/M3', 1, 0, 'RC');
            $pdf->Cell(2, 0.5, 'HARGA', 1, 0, 'C');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'AFKIR', 1, 0, 'C');
            $pdf->Cell(0.8, 0.5, 'PCS', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'C');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'RENCEK', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $ar['j_c_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $ar['j_c_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(2, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'RENCEK', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $ar['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $ar['j_afkir_m3']+0, 1, 0, 'R');
            $pdf->Cell(1, 1, '', 0, 0, 'C');
            $pdf->SetFont('arial','',9);
            $pdf->Cell(2.4, 1, 'TOTAL+AFKIR', 1, 0, 'C');
            $total_afkir =  $this->Rekap_total->format_angka($total_afkir_m3+$total_a_m3+$total_b_satum_m3+$total_c_m3);
            $pdf->SetFont('arial','b',9);
            $pdf->Cell(1.2, 0.5,  $this->Rekap_total->cetak_angka($total_afkir), 1, 0, 'R');
            $pdf->SetFont('arial','',9);
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'L');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A0 (9-14)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a0['j_c_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a0['j_c_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[14]), 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($c_a0), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A0 (9-14)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a0['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a0['j_afkir_m3']), 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0,0,'C');
            $pdf->SetFont('arial','U',8);
            $pdf->Cell(2.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','b',9);
            $total_pc = $total_afkir_pc+$total_a_pc+$total_b_satum_pc+$total_c_pc;
            $pdf->Cell(1.2, 0.5, $this->Rekap_total->format_harga($total_pc), 1, 0, 'R');
            $pdf->SetFont('arial','',9);
            $pdf->Cell(1.7, 0.5, 'BATANG', 1, 0, 'L');
            //garis baru
            $pdf->ln(0.5);

            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A1 (16-18)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a1['j_c_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a1['j_c_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[15]), 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($c_a1), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A1 (16-18)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a1['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a1['j_afkir_m3']), 1, 0, 'R');
            $pdf->Cell(1, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(2.4, 1, 'TOTAL BERSIH', 1, 0, 'C');
            $pdf->SetFont('arial','b',9);
            $total_bersih = $total_a_m3+$total_b_satum_m3+$total_c_m3;
            $pdf->Cell(1.2, 0.5, $this->Rekap_total->cetak_angka($total_bersih), 1, 0, 'R');
            $pdf->SetFont('arial','',9);
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'L');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2.1 (20-24)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a21['j_c_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a21['j_c_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[16]), 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($c_a21), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2.1 (20-24)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a21['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a21['j_afkir_m3']), 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(2.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','b',9);
            $total_pc2 = $total_a_pc+$total_b_satum_pc+$total_c_pc;
            $pdf->Cell(1.2, 0.5, $this->Rekap_total->format_harga($total_pc2), 1, 0, 'R');
            $pdf->SetFont('arial','',9);
            $pdf->Cell(1.7, 0.5, 'BATANG', 1, 0, 'L');
            //garis baru
            $pdf->ln(0.5);

            $pdf->SetFont('arial','',8);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2.2 (25-29)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a22['j_c_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a22['j_c_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[17]), 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($c_a22), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2.2 (25-29)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a22['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a22['j_afkir_m3']), 1, 0, 'R');
            $pdf->Cell(1, 0.5, '', 0, 0, 'C');
            $pdf->Cell(2.4, 0.5, 'HARGA', 1, 0, 'C');
            $total_harga = $total_a_harga+$total_b_satum_harga+$total_c_harga;
            $pdf->SetFont('arial','b',10);
            $pdf->Cell(2.9, 0.5, 'Rp. '.$this->Rekap_total->format_harga($total_harga), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);

            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A3 (30-39)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a3['j_c_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a3['j_c_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[18]), 1, 0, 'R');
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($c_a3), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A3 (30-39)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a3['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a3['j_afkir_m3']), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A4 (40-Up)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a4['j_c_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a4['j_c_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[19]), 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($c_a4), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A4 (40-Up)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a4['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a4['j_afkir_m3']), 1, 0, 'R');

            $pdf->ln(0.5);

            $pdf->SetFont('arial','b',9);
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $total_c_pc, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($total_c_m3), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'L');
            $pdf->Cell(2, 0.5, 'Rp. '.$this->Rekap_total->format_harga($total_c_harga), 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','b',6);
            $pdf->Cell(1.7, 0.5, 'TOTAL AFKIR', 1, 0, 'L');
            $pdf->SetFont('arial','b',9);
            $pdf->Cell(0.8, 0.5, $total_afkir_pc, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($total_afkir_m3), 1, 0, 'R');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1, 0.5, '', 0, 0, 'C');
            $pdf->Cell(2.4, 0.5, 'DIBUAT OLEH', 0, 0, 'L');
            $pdf->Cell(2.9, 0.5, ': '.$this->session->userdata('nama'), 0, 0, 'L');

          $pdf->Output("Rekap Log-".$data['bpk']['no_bpk']."pdf","I");

        }

        // BPK NON SENGON
        else {
          $data['serah_terima_log'] = $this->Serah_terima_log_model->get_all_serah_terima_log($this->session->userdata('no_bpk'));

          $data['rekap_pembayaran_log'] = $this->Rekap_pembayaran_log_model->get_rekap_pembayaran_log($this->session->userdata('no_bpk'));
          $data['harga_m3'] = $this->Rekap_pembayaran_log_model->get_harga_m3();

          foreach ($data['harga_m3'] as $h) {
                $harga[] = $h['harga'];
          }

          $ar = $this->Rekap_total->get_ar($this->session->userdata('no_bpk'));
          $a0 = $this->Rekap_total->get_a0($this->session->userdata('no_bpk'));
          $a1 = $this->Rekap_total->get_a1($this->session->userdata('no_bpk'));
          $a21 = $this->Rekap_total->get_a21($this->session->userdata('no_bpk'));
          $a22 = $this->Rekap_total->get_a22($this->session->userdata('no_bpk'));
          $a3 = $this->Rekap_total->get_a3($this->session->userdata('no_bpk'));
          $a4 = $this->Rekap_total->get_a4($this->session->userdata('no_bpk'));

          $total_afkir_m3 = $a0['j_afkir_m3']+$a1['j_afkir_m3']+$a21['j_afkir_m3']+$a22['j_afkir_m3']+$a3['j_afkir_m3']+$a4['j_afkir_m3']+$ar['j_afkir_m3'];

          $total_b_m3 =  $a0['j_b_m3']+$a1['j_b_m3']+$a21['j_b_m3']+$a22['j_b_m3']+$a3['j_b_m3']+$a4['j_b_m3']+$ar['j_b_m3'];

          $total_b_pc  = $a0['j_b_pc']+$a1['j_b_pc']+$a21['j_b_pc']+$a22['j_b_pc']+$a3['j_b_pc']+$a4['j_b_pc']+$ar['j_b_pc'];

          $b_a0 = $harga[35]* $this->Rekap_total->format_angka($a0['j_b_m3']);
          $b_a1 = $harga[36]* $this->Rekap_total->format_angka($a1['j_b_m3']);
          $b_a21 = $harga[37]* $this->Rekap_total->format_angka($a21['j_b_m3']);
          $b_a22 = $harga[38]* $this->Rekap_total->format_angka($a22['j_b_m3']);
          $b_a3 = $harga[39]* $this->Rekap_total->format_angka($a3['j_b_m3']);
          $b_a4 = $harga[40]* $this->Rekap_total->format_angka($a4['j_b_m3']);
          $total_b_harga  = $b_a0+$b_a1+$b_a21+$b_a22+$b_a3+$b_a4;

          $satum_a0 = $harga[42]*$this->Rekap_total->format_angka($a0['j_satum_m3']);
          $satum_a1 = $harga[43]*$this->Rekap_total->format_angka($a1['j_satum_m3']);
          $satum_a21 = $harga[44]*$this->Rekap_total->format_angka($a21['j_satum_m3']);
          $satum_a22 = $harga[45]*$this->Rekap_total->format_angka($a22['j_satum_m3']);
          $satum_a3 = $harga[46]*$this->Rekap_total->format_angka($a3['j_satum_m3']);
          $satum_a4 = $harga[47]*$this->Rekap_total->format_angka($a4['j_satum_m3']);

          $total_afkir_pc = $a0['j_afkir_pc']+$a1['j_afkir_pc']+$a21['j_afkir_pc']+$a22['j_afkir_pc']+$a3['j_afkir_pc']+$a4['j_afkir_pc']+$ar['j_afkir_pc'];

          $pdf = new FPDF("P","cm","A4");

            $pdf->SetMargins(1,1,1);
            $pdf->AliasNbPages();
            $pdf->AddPage();

            $pdf->SetFont('arial','B',10);
            $pdf->Cell(2.3, 0.8, 'PT. SUMBER ALAM SANTOSO PRATAMA', 0, 0, 'L');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',10);
            $pdf->Cell(11.5, 0.8, 'Dusun Nganjukan RT 05 RW 03', 0, 0, 'L');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1, 0.8, 'NAMA', 0, 0, 'L');
            $pdf->Cell(0.5, 0.8, ':', 0, 0, 'L');
            $pdf->Cell(2.5, 0.8, $data['bpk']['nama_supplier'], 0, 0, 'L');
            $pdf->Cell(1, 0.8, 'NOPOL', 0, 0, 'L');
            $pdf->Cell(0.5, 0.8, ':', 0, 0, 'L');
            $pdf->Cell(2, 0.8, $data['bpk']['no_polisi'], 0, 0, 'L');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',10);
            $pdf->Cell(11.5, 0.8, 'Desa Karangsari Kec. Sempu', 0, 0, 'L');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1, 0.8, 'TGL', 0, 0, 'L');
            $pdf->Cell(0.5, 0.8, ':', 0, 0, 'L');
            $pdf->Cell(2.5, 0.8, $this->Bpk_model->IndonesiaTgl($data['bpk']['tanggal']), 0, 0, 'L');
            $pdf->Cell(1, 0.8, 'KET', 0, 0, 'L');
            $pdf->Cell(0.5, 0.8, ':', 0, 0, 'L');
            $pdf->Cell(2, 0.8, $data['bpk']['jenis_kayu'], 0, 0, 'L');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',10);
            $pdf->Cell(6, 0.8, 'Banyuwangi', 0, 0, 'L');
            $pdf->SetFont('arial','B',10);
            $pdf->Cell(5.5,0.7,'REKAP PEMBAYARAN LOG',0,0,'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1, 0.8, 'BPK', 0, 0, 'L');
            $pdf->Cell(0.5, 0.8, ':', 0, 0, 'L');
            $pdf->Cell(2.5, 0.8, $data['bpk']['no_bpk'], 0, 0, 'L');

            $pdf->ln(1);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, '1.3 M', 1, 0, 'C');
            $pdf->Cell(0.8, 0.5, 'PCS', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'HARGA/M3', 1, 0, 'C');
            $pdf->Cell(2, 0.5, 'HARGA', 1, 0, 'C');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, '1M', 1, 0, 'C');
            $pdf->Cell(0.8, 0.5, 'PCS', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'HARGA/M3', 1, 0, 'C');
            $pdf->Cell(2, 0.5, 'HARGA', 1, 0, 'C');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'RENCEK', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $ar['j_a_pc'], 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($ar['j_a_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(2, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'RENCEK', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $ar['j_satum_pc'], 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $ar['j_satum_m3'], 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(2, 0.5, '-', 1, 0, 'R');
            $pdf->ln(0.5);

            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A0 (9-14)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a0['j_a_pc'], 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a0['j_a_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '-', 1, 0, 'R');
            $a_a0 = $harga[28]*$this->Rekap_total->format_angka($a0['j_a_m3']);
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($a_a0), 1, 0, 'R');
            $pdf->Cell(0.7, 0.8, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A0 (9-14)', 1, 0, 'L');
            $pdf->SetFont('arial','',10);
            $pdf->Cell(0.8, 0.5, $a0['j_satum_pc'], 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->cetak_angka($a0['j_satum_m3']), 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($satum_a0), 1, 0, 'R');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A1 (16-18)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a1['j_a_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a1['j_a_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[29]), 1, 0, 'R');
            $a_a1 = $harga[29]*$a1['j_a_m3'];
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($a_a1), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'A1 (16-18)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a1['j_satum_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a1['j_satum_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[43]), 1, 0, 'R');
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($satum_a1), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2.1 (20-24)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a21['j_a_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a21['j_a_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[30]), 1, 0, 'R');
            $a_a21 = $harga[30]*$a21['j_a_m3'];
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($a_a21), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'A2 (20-24)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a21['j_satum_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a21['j_satum_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[44]), 1, 0, 'R');

            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($satum_a21), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2.2 (25-29)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a22['j_a_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a22['j_a_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[31]), 1, 0, 'R');
            $a_a22 = $harga[31]*$a22['j_a_m3'];
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($a_a22), 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'A2.2 (25-29)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a22['j_satum_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a22['j_satum_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[45]), 1, 0, 'R');

            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($satum_a22), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A3 (30-39)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a3['j_a_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a3['j_a_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[32]), 1, 0, 'R');
            $a_a3 = $harga[32]*$a3['j_a_m3'];
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($a_a3) , 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'R');
            $pdf->Cell(1.7, 0.5, 'A3 (30-39)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a3['j_satum_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a3['j_satum_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[46]), 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($satum_a3), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A4 (40-Up)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a4['j_a_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a4['j_a_pc']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[33]), 1, 0, 'R');

            $a_a4 = $harga[33]*$a4['j_a_m3'];
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($a_a4), 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'A4 (40-Up)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a4['j_satum_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a4['j_satum_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[47]), 1, 0, 'R');

            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($satum_a4), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $total_a_pc = $a0['j_a_pc']+$a1['j_a_pc']+$a21['j_a_pc']+$a22['j_a_pc']+$a3['j_a_pc']+$a4['j_a_pc']+$ar['j_a_pc'], 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $total_a_m3 = $a0['j_a_m3']+$a1['j_a_m3']+$a21['j_a_m3']+$a22['j_a_m3']+$a3['j_a_m3']+$a4['j_a_m3']+$ar['j_a_m3'], 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'L');
            $total_a_harga = $a_a0+$a_a1+$a_a21+$a_a22+$a_a3+$a_a4;
            $pdf->Cell(2, 0.5, 'Rp. '.$this->Rekap_total->format_harga($total_a_harga), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $total_satum_pc = $a0['j_satum_pc']+$a1['j_satum_pc']+$a21['j_satum_pc']+$a22['j_satum_pc']+$a3['j_satum_pc']+$a4['j_satum_pc']+$ar['j_satum_pc'], 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $total_b_satum_m3 = $a0['j_satum_m3']+$a1['j_satum_m3']+$a21['j_satum_m3']+$a22['j_satum_m3']+$a3['j_satum_m3']+$a4['j_satum_m3']+$ar['j_satum_m3'], 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'R');
            $total_satum_harga = $satum_a0+$satum_a1+$satum_a21+$satum_a22+$satum_a3+$satum_a4;
            $pdf->Cell(2, 0.5, 'Rp. '.$this->Rekap_total->format_harga($total_satum_harga), 1, 0, 'R');
            //garis baru
            $pdf->ln(1.2);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'B', 1, 0, 'C');
            $pdf->Cell(0.8, 0.5, 'PCS', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'HARGA/M3', 1, 0, 'RC');
            $pdf->Cell(2, 0.5, 'HARGA', 1, 0, 'C');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'AFKIR', 1, 0, 'C');
            $pdf->Cell(0.8, 0.5, 'PCS', 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'C');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'RENCEK', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $ar['j_b_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $ar['j_b_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(2, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'RENCEK', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $ar['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $ar['j_afkir_m3']+0, 1, 0, 'R');
            $pdf->Cell(1, 1, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(2.4, 1, 'TOTAL+AFKIR', 1, 0, 'C');
            $pdf->Cell(1.2, 0.5, $total_afkir_m3+$total_a_m3+$total_b_satum_m3+$total_b_m3, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'L');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A0 (9-14)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a0['j_b_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a0['j_b_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '-', 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($b_a0), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'A0 (9-14)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a0['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a0['j_afkir_m3']+0, 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0,0,'C');
            $pdf->SetFont('arial','U',8);
            $pdf->Cell(2.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.2, 0.5, $total_afkir_pc+$total_a_pc+$total_satum_pc+$total_b_pc, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, 'BATANG', 1, 0, 'L');
            //garis baru
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A1 (16-18)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a1['j_b_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a1['j_b_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[36]), 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($b_a1), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'A1 (16-18)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a1['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a1['j_afkir_pc']+0, 1, 0, 'R');
            $pdf->Cell(1, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(2.4, 1, 'TOTAL BERSIH', 1, 0, 'C');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.2, 0.5, $total_a_m3+$total_b_satum_m3+$total_b_m3, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, 'M3', 1, 0, 'L');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2.1 (20-24)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a21['j_b_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a21['j_b_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[37]), 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($b_a21), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'A2.1 (20-24)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a21['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a21['j_afkir_m3']+0, 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(2.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.2, 0.5, $total_a_pc+$total_satum_pc+$total_b_pc, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, 'BATANG', 1, 0, 'L');
            //garis baru
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A2.2 (25-29)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a22['j_b_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a22['j_b_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[38]), 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($b_a22), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'A2.2 (25-29)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a22['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a22['j_afkir_m3']+0, 1, 0, 'R');
            $pdf->Cell(1, 0.5, '', 0, 0, 'C');
            $pdf->Cell(2.4, 0.5, 'HARGA', 1, 0, 'C');
            $total_harga = $total_a_harga+$total_satum_harga+$total_b_harga;
            $pdf->Cell(2.9, 0.5, 'Rp. '.$this->Rekap_total->format_harga($total_harga), 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A3 (30-39)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a3['j_b_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a3['j_b_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[39]), 1, 0, 'R');
            $pdf->Cell(2, 0.5,$this->Rekap_total->format_harga($b_a3), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'A3 (30-39)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a3['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a3['j_afkir_m3']+0, 1, 0, 'R');
            //garis baru
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, 'A4 (40-Up)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a4['j_b_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a4['j_b_m3']+0, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $this->Rekap_total->format_harga($harga[40]), 1, 0, 'R');
            $pdf->Cell(2, 0.5, $this->Rekap_total->format_harga($b_a4), 1, 0, 'R');

            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->Cell(1.7, 0.5, 'A4 (40-Up)', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $a4['j_afkir_pc']+0, 1, 0, 'C');
            $pdf->Cell(1.7, 0.5, $a4['j_afkir_m3']+0, 1, 0, 'R');
            $pdf->ln(0.5);
            $pdf->SetFont('arial','',8);
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'L');
            $pdf->Cell(0.8, 0.5, $total_b_pc, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $total_b_m3, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, '', 1, 0, 'L');
            $pdf->Cell(2, 0.5, 'Rp. '.$this->Rekap_total->format_harga($total_b_harga), 1, 0, 'R');
            $pdf->Cell(0.7, 0.5, '', 0, 0, 'C');
            $pdf->SetFont('arial','',7);
            $pdf->Cell(1.7, 0.5, 'TOTAL AFKIR', 1, 0, 'L');
            $pdf->SetFont('arial','',8);
            $pdf->Cell(0.8, 0.5, $total_afkir_pc, 1, 0, 'R');
            $pdf->Cell(1.7, 0.5, $total_afkir_m3, 1, 0, 'R');


          $pdf->SetFont('arial','',8);
          $pdf->Cell(1, 0.5, '', 0, 0, 'C');
          $pdf->Cell(2.4, 0.5, 'DIBUAT OLEH', 0, 0, 'L');
          $pdf->Cell(2.9, 0.5, ': '.$this->session->userdata('nama'), 0, 0, 'L');
          $pdf->Output("Rekap Log-NS_".$data['bpk']['no_bpk']."pdf","I");
        }
    }

    /*
     * Adding a new serah_terima_log
     */
    public function add()
    {
      $data['serah_terima_log'] = $this->Serah_terima_log_model->get_all_serah_terima_log($this->session->userdata('no_bpk'));

      $data['_view'] = 'serah_terima_log/add';

        $this->load->library('form_validation');

		$this->form_validation->set_rules('diameter','Diameter','required|integer');
		$this->form_validation->set_rules('grade_grade','Grade Grade','required|max_length[5]');

		if($this->form_validation->run())
        {
            $params = array(
				'no_log' => $this->input->post('no_log'),
				'diameter' => $this->input->post('diameter'),
				'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
				'grade_grade' => $this->input->post('grade_grade'),
            );

            $serah_terima_log_id = $this->Serah_terima_log_model->add_serah_terima_log($params);
            $this->Rekap_pembayaran_log_model->rekap_log($params['bpk_no_bpk'], $params['grade_grade'],$params['diameter']);
            $this->Cek_log_model->cek_log($params['bpk_no_bpk'], $params['grade_grade'],$params['diameter']);
            $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'], $params['grade_grade'],$params['diameter']);
            redirect('serah_terima_log/add/'.$params['bpk_no_bpk']);

            //session simpan bpk
        }
        else
        {
            $data['_view'] = 'serah_terima_log/add';
            $this->load->view('layouts/main',$data);
        }
    }

    public function upload(){
  		$fileName = time().$_FILES['file']['name'];

  		$config['upload_path'] = './assets/xls_file/'; //buat folder dengan nama assets di root folder
  		$config['file_name'] = $fileName;
  		$config['allowed_types'] = 'xls|xlsx|csv';
  		$config['max_size'] = 10000;

  		$this->load->library('upload');
  		$this->upload->initialize($config);

  		if(! $this->upload->do_upload('file') )
  		$this->upload->display_errors();

  		$media = $this->upload->data('file');
  		$inputFileName = './assets/xls_file/'.$media['file_name'];

  		try {
  				$inputFileType = IOFactory::identify($inputFileName);
  				$objReader = IOFactory::createReader($inputFileType);
  				$objPHPExcel = $objReader->load($inputFileName);
  			} catch(Exception $e) {
  				die('Error loading file "'.pathinfo($inputFileName,PATHINFO_BASENAME).'": '.$e->getMessage());
  			}

  			$sheet = $objPHPExcel->getSheet(0);
  			$highestRow = $sheet->getHighestRow();
  			$highestColumn = $sheet->getHighestColumn();

  			for ($row = 2; $row <= $highestRow; $row++){                  //  Read a row of data into an array
  				$rowData = $sheet->rangeToArray('A' . $row . ':' . $highestColumn . $row,
  												NULL,
  												TRUE,
  												FALSE);

  				//Sesuaikan sama nama kolom tabel di database
  				 $data = array(
  					"no_log"=> $rowData[0][0],
  					"diameter"=> $rowData[0][1],
  					"bpk_no_bpk"=> $rowData[0][2],
  					"grade_grade"=> $rowData[0][3]
  				);
  				//sesuaikan nama dengan nama tabel
  				$insert = $this->db->insert("serah_terima_log",$data);
  				//delete_files($media['file_path']);

  			}
  		redirect('serah_terima_log/');
  	}
    /*
     * Editing a serah_terima_log
     */
    public function edit($id)
    {
        // check if the serah_terima_log exists before trying to edit it

        $data['serah_terima_log'] = $this->Serah_terima_log_model->get_serah_terima_log($id);

        if(isset($data['serah_terima_log']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('diameter','Diameter','required|integer');
			$this->form_validation->set_rules('grade_grade','Grade Grade','required|max_length[5]');

			if($this->form_validation->run())
            {
                $params = array(
					'no_log' => $this->input->post('no_log'),
					'diameter' => $this->input->post('diameter'),
					'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
					'grade_grade' => $this->input->post('grade_grade'),
                );

                $this->Serah_terima_log_model->update_serah_terima_log($id,$params);

                $this->Rekap_pembayaran_log_model->rekap_log($this->session->userdata('no_bpk'), $data['serah_terima_log']['grade_grade'],$data['serah_terima_log']['diameter']);

                $this->Cek_log_model->cek_log($this->session->userdata('no_bpk'), $data['serah_terima_log']['grade_grade'],$data['serah_terima_log']['diameter']);

                $this->Selisih_stok_model->selisih_stok($this->session->userdata('no_bpk'), $data['serah_terima_log']['grade_grade'],$data['serah_terima_log']['diameter']);

                $this->Rekap_pembayaran_log_model->rekap_log($params['bpk_no_bpk'], $params['grade_grade'],$params['diameter']);

                $this->Cek_log_model->cek_log($params['bpk_no_bpk'], $params['grade_grade'],$params['diameter']);

                $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'], $params['grade_grade'],$params['diameter']);

                redirect('serah_terima_log/index');
            }
            else
            {
                $data['_view'] = 'serah_terima_log/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The serah_terima_log you are trying to edit does not exist.');
    }

    public function detail_bpk($no_bpk)
    {
        // check if the serah_terima_log exists before trying to edit it
        $data['serah_terima_log'] = $this->Serah_terima_log_model->get_serah_terima_bpk($no_bpk);

        $data['_view'] = 'serah_terima_log/detail_bpk';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Deleting serah_terima_log
     */
    public function remove($id)
    {
        $serah_terima_log = $this->Serah_terima_log_model->get_serah_terima_log($id);

        // check if the serah_terima_log exists before trying to delete it
        if(isset($serah_terima_log['id']))
        {
            $this->Serah_terima_log_model->delete_serah_terima_log($id);

            $this->Rekap_pembayaran_log_model->rekap_log($serah_terima_log['bpk_no_bpk'], $serah_terima_log['grade_grade'],$serah_terima_log['diameter']);

            $this->Cek_log_model->cek_log($serah_terima_log['bpk_no_bpk'], $serah_terima_log['grade_grade'],$serah_terima_log['diameter']);

            $this->Selisih_stok_model->selisih_stok($serah_terima_log['bpk_no_bpk'], $serah_terima_log['grade_grade'],$serah_terima_log['diameter']);

            redirect('serah_terima_log/index');
        }
        else
            show_error('The serah_terima_log you are trying to delete does not exist.');
    }

}
