<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Log_rotary extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bpk_model');
        $this->load->model('Log_rotary_model');
        $this->load->model('Bongkar_log_model');
        $this->load->model('Cek_log_model');
        $this->load->model('Selisih_stok_model');
    }

    /*
     * Listing of log_rotary
     */
    function index()
    {
        $data['log_rotary'] = $this->Log_rotary_model->get_all_log_rotary($this->session->userdata('no_bpk'));

        $data['_view'] = 'log_rotary/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new log_rotary
     */
    function add()
    {

      $data['log_rotary'] = $this->Log_rotary_model->get_all_log_rotary($this->session->userdata('no_bpk'));

        $this->load->library('form_validation');

    $this->form_validation->set_rules('no','No','required|integer');
    $this->form_validation->set_rules('diameter','Diameter','required|integer');
		$this->form_validation->set_rules('grade_grade','Grade Grade','required|max_length[5]');

		if($this->form_validation->run())
        {
            $params = array(
				'no' => $this->input->post('no'),
				'diameter' => $this->input->post('diameter'),
				'tanggal' => $this->Bpk_model->InggrisTgl($this->input->post('tanggal')),
        'grade_grade' => $this->input->post('grade_grade'),
        'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
            );

            $selisih = $this->Selisih_stok_model->cek_selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

            if ($selisih>=1) {
            $log_rotary_id = $this->Log_rotary_model->add_log_rotary($params);
            $this->Bongkar_log_model->bongkar_log_rotary($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

            $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

            $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

            redirect('log_rotary/add');
          } else {
            $data['gagal'] = 'stok yang anda masukkan sudah tidak ada !! ulangi perintah';
            $data['_view'] = 'log_rotary/add';
            $this->load->view('layouts/main',$data);
          }
        }
        else
        {
            $data['_view'] = 'log_rotary/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a log_rotary
     */
    function edit($id)
    {
        // check if the log_rotary exists before trying to edit it
        $data['log_rotary'] = $this->Log_rotary_model->get_log_rotary($id);
        $result = $this->Log_rotary_model->get_log_rotary($id);

        if(isset($data['log_rotary']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('diameter','Diameter','required|integer');
			$this->form_validation->set_rules('grade_grade','Grade Grade','required|max_length[5]');

			if($this->form_validation->run())
            {
                $params = array(
					'no' => $this->input->post('no'),
					'diameter' => $this->input->post('diameter'),
          'tanggal' => $this->Bpk_model->InggrisTgl($this->input->post('tanggal')),
          'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
					'grade_grade' => $this->input->post('grade_grade'),
                );

                $this->Log_rotary_model->update_log_rotary($id,$params);

                $this->Bongkar_log_model->bongkar_log_rotary($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Bongkar_log_model->bongkar_log_rotary($params['bpk_no_bpk'],$data['log_rotary']['grade_grade'],$data['log_rotary']['diameter']);

                $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$data['log_rotary']['grade_grade'],$data['log_rotary']['diameter']);

                $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$data['log_rotary']['grade_grade'],$data['log_rotary']['diameter']);

                redirect('cek_log/index');
            }
            else
            {
                $data['_view'] = 'log_rotary/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The log_rotary you are trying to edit does not exist.');
    }

    /*
     * Deleting log_rotary
     */
    function remove($id)
    {
        $log_rotary = $this->Log_rotary_model->get_log_rotary($id);

        // check if the log_rotary exists before trying to delete it
        if(isset($log_rotary['id']))
        {
            $this->Log_rotary_model->delete_log_rotary($id);

            $this->Bongkar_log_model->bongkar_log_rotary($log_rotary['bpk_no_bpk'],$log_rotary['grade_grade'],$log_rotary['diameter']);

            $this->Cek_log_model->cek_log($log_rotary['bpk_no_bpk'],$log_rotary['grade_grade'],$log_rotary['diameter']);

            $this->Selisih_stok_model->selisih_stok($log_rotary['bpk_no_bpk'],$log_rotary['grade_grade'],$log_rotary['diameter']);
            redirect('cek_log/index');
        }
        else
            show_error('The log_rotary you are trying to delete does not exist.');
    }

    function removeall($bpk)
    {
            $rotary = $this->Log_rotary_model->get_all_log_rotary($bpk);

            foreach ($rotary as $r) {
              $this->Log_rotary_model->delete_log_rotary($r['id']);
              $this->Bongkar_log_model->bongkar_log_rotary($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
              $this->Cek_log_model->cek_log($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
              $this->Selisih_stok_model->selisih_stok($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
            }


            redirect('cek_log/index');
    }

}
