<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Bansaw3_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get bansaw3 by id
     */
    function get_bansaw3($id)
    {
        return $this->db->get_where('bansaw3',array('id'=>$id))->row_array();
    }

    /*
     * Get all bansaw3
     */
    function get_all_bansaw3($id)
    {
        return $this->db->get_where('bansaw3',array('bpk_no_bpk'=>$id))->result_array();
    }

    /*
     * function to add new bansaw3
     */
    function add_bansaw3($params)
    {
        $this->db->insert('bansaw3',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update bansaw3
     */
    function update_bansaw3($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('bansaw3',$params);
        if($response)
        {
            return "bansaw3 updated successfully";
        }
        else
        {
            return "Error occuring while updating bansaw3";
        }
    }

    /*
     * function to delete bansaw3
     */
    function delete_bansaw3($id)
    {
        $response = $this->db->delete('bansaw3',array('id'=>$id));
        if($response)
        {
            return "bansaw3 deleted successfully";
        }
        else
        {
            return "Error occuring while deleting bansaw3";
        }
    }

    function get_number($id){
      $nomor = $this->db->get_where('bansaw3',array('bpk_no_bpk'=>$id));
      $no = $nomor->num_rows();
      return $no+1;
    }
}
