<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Bansaw2_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get bansaw2 by id
     */
    function get_bansaw2($id)
    {
        return $this->db->get_where('bansaw2',array('id'=>$id))->row_array();
    }

    /*
     * Get all bansaw2
     */
    function get_all_bansaw2($no_bpk)
    {
        return $this->db->get_where('bansaw2',array('bpk_no_bpk'=>$no_bpk))->result_array();
    }

    /*
     * function to add new bansaw2
     */
    function add_bansaw2($params)
    {
        $this->db->insert('bansaw2',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update bansaw2
     */
    function update_bansaw2($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('bansaw2',$params);
        if($response)
        {
            return "bansaw2 updated successfully";
        }
        else
        {
            return "Error occuring while updating bansaw2";
        }
    }

    /*
     * function to delete bansaw2
     */
    function delete_bansaw2($id)
    {
        $response = $this->db->delete('bansaw2',array('id'=>$id));
        if($response)
        {
            return "bansaw2 deleted successfully";
        }
        else
        {
            return "Error occuring while deleting bansaw2";
        }
    }

    function get_number($id){
      $nomor = $this->db->get_where('bansaw2',array('bpk_no_bpk'=>$id));
      $no = $nomor->num_rows();
      return $no+1;
    }
}
