<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Bongkar_log_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get bongkar_log by id
     */
    function get_bongkar_log($id)
    {
        return $this->db->get_where('bongkar_log',array('id'=>$id))->row_array();
    }

    /*
     * Get all bongkar_log
     */
    function get_all_bongkar_log($no_bpk)
    {
        return $this->db->get_where('bongkar_log',array('bpk_no_bpk'=>$no_bpk))->result_array();
    }

    function get_total_bongkar_log($id)
    {
        return $this->db->get_where('v_bongkar_log',array('no_bpk'=>$id))->row_array();
    }

    function get_pemakaian_log()
    {
      return $this->db->get('v_pemakaian')->result_array();
    }

    function get_total_pemakaian()
    {
      return $this->db->get('v_total_pemakaian')->result_array();
    }

    //export excel
    function pemakaian_skr($tanggal)
    {
      return $this->db->query("select * from v_pemakaian where tanggal between '$tanggal-1' and '$tanggal-31'")->result_array();
    }

    /*
     * function to add new bongkar_log
     */
    function add_bongkar_log($params)
    {
        $this->db->insert('bongkar_log',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update bongkar_log
     */
    function update_bongkar_log($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('bongkar_log',$params);
        if($response)
        {
            return "bongkar_log updated successfully";
        }
        else
        {
            return "Error occuring while updating bongkar_log";
        }
    }

    function bongkar_log_rotary($no_bpk, $grade, $diameter)
    {
      $jml_rotary = $this->db->get_where('log_rotary', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw1 = $this->db->get_where('bansaw1', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw2 = $this->db->get_where('bansaw2', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw3 = $this->db->get_where('bansaw3', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $total_pc = $jml_rotary->num_rows() + $jml_bansaw1->num_rows() + $jml_bansaw2->num_rows() + $jml_bansaw3->num_rows();
      $count = $jml_rotary->num_rows();


      if($grade == "A" || $grade == "a"){
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'a_rot' => $count,
                'a_m3' => $kubik*$total_pc,
              );
              $response = $this->db->update('bongkar_log',$params);

      } else if($grade == 'B' || $grade == "b"){
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'b_rot' => $count,
                'b_m3' => $kubik*$total_pc,
              );
              $response = $this->db->update('bongkar_log',$params);

      }else if($grade == 'C' || $grade == "c"){
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'c_rot' => $count,
                'c_m3' => $kubik*$total_pc,
              );
              $response = $this->db->update('bongkar_log',$params);

      } else if($grade == '1M' || $grade == "1m"){
      $jml_kubik = $this->db->query("select satum from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satum;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'satum_rot' => $count,
                'satum_m3' => $kubik*$total_pc,
              );
              $response = $this->db->update('bongkar_log',$params);

      } else if($grade == 'AF' || $grade == "af" || $grade == "Af"){
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'afkir_rot' => $count,
                'afkir_m3' => $kubik*$total_pc,
              );
              $response = $this->db->update('bongkar_log',$params);
      }
    }

    function bongkar_log_bansaw1($no_bpk, $grade, $diameter)
    {
      $jml_rotary = $this->db->get_where('log_rotary', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw1 = $this->db->get_where('bansaw1', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw2 = $this->db->get_where('bansaw2', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw3 = $this->db->get_where('bansaw3', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $total_pc = $jml_rotary->num_rows() + $jml_bansaw1->num_rows() + $jml_bansaw2->num_rows() + $jml_bansaw3->num_rows();
      $count = $jml_bansaw1->num_rows();

      if($grade == "A" || $grade == "a"){
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'a_band1' => $count,
                'a_m3' => $kubik*$total_pc,
              );
      } else if($grade == 'B' || $grade == "b"){
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'b_band1' => $count,
                'b_m3' => $kubik*$total_pc,
              );
      }else if($grade == 'C' || $grade == "c"){
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'c_band1' => $count,
                'c_m3' => $kubik*$total_pc,
              );
      } else if($grade == '1M' || $grade == "1m"){
      $jml_kubik = $this->db->query("select satum from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satum;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'satum_band1' => $count,
                'satum_m3' => $kubik*$total_pc,
              );
      } else if($grade == 'AF' || $grade == "af" || $grade == "Af"){
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'afkir_band1' => $count,
                'afkir_m3' => $kubik*$total_pc,
              );
      }
      $response = $this->db->update('bongkar_log',$params);
    }

    function bongkar_log_bansaw2($no_bpk, $grade, $diameter)
    {
      $jml_rotary = $this->db->get_where('log_rotary', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw1 = $this->db->get_where('bansaw1', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw2 = $this->db->get_where('bansaw2', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw3 = $this->db->get_where('bansaw3', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $total_pc = $jml_rotary->num_rows() + $jml_bansaw1->num_rows() + $jml_bansaw2->num_rows() + $jml_bansaw3->num_rows();
      $count = $jml_bansaw2->num_rows();

      if($grade == "A" || $grade == "a"){
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'a_band2' => $count,
                'a_m3' => $kubik*$total_pc,
              );
      } else if($grade == 'B' || $grade == "b"){
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;  $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'b_band2' => $count,
                'b_m3' => $kubik*$total_pc,
              );
      } else if($grade == 'C' || $grade == "c"){
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;  $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'c_band2' => $count,
                'c_m3' => $kubik*$total_pc,
              );
      }else if($grade == '1M' || $grade == "1m"){
      $jml_kubik = $this->db->query("select satum from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satum;
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'satum_band2' => $count,
                'satum_m3' => $kubik*$total_pc,
              );
      } else if($grade == 'AF' || $grade == "af" || $grade == "Af"){
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $params = array(
                'afkir_band2' => $count,
                'afkir_m3' => $kubik*$total_pc,
              );
      }
      $response = $this->db->update('bongkar_log',$params);
    }

    function bongkar_log_bansaw3($no_bpk, $grade, $diameter)
    {
      $jml_rotary = $this->db->get_where('log_rotary', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw1 = $this->db->get_where('bansaw1', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw2 = $this->db->get_where('bansaw2', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_bansaw3 = $this->db->get_where('bansaw3', array('grade_grade'=>$grade,'diameter'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $total_pc = $jml_rotary->num_rows() + $jml_bansaw1->num_rows() + $jml_bansaw2->num_rows() + $jml_bansaw3->num_rows();
      $count = $jml_bansaw3->num_rows();

      if($grade == "A" || $grade == "a"){
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $params = array(
                'a_band3' => $count,
                'a_m3' => $kubik*$total_pc,
              );
      } else if($grade == 'B' || $grade == "b"){
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $params = array(
                'b_band3' => $count,
                'b_m3' => $kubik*$total_pc,
              );
      } else if($grade == 'C' || $grade == "c"){
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $params = array(
                'c_band3' => $count,
                'c_m3' => $kubik*$total_pc,
              );
      }  else if($grade == '1M' || $grade == "1m"){
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_kubik = $this->db->query("select satum from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satum;
      $params = array(
                'satum_band3' => $count,
                'satum_m3' => $kubik*$total_pc,
              );
      } else if($grade == 'AF' || $grade == "af" || $grade == "Af"){
      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $jml_kubik = $this->db->query("select satutigam from kubik where id='$diameter'");
      $k = $jml_kubik->row();
      $kubik = $k->satutigam;
      $params = array(
                'afkir_band3' => $count,
                'afkir_m3' => $kubik*$total_pc,
              );
      }
      $response = $this->db->update('bongkar_log',$params);
    }

    /*
     * function to delete bongkar_log
     */
    function delete_bongkar_log($id)
    {
        $response = $this->db->delete('bongkar_log',array('id'=>$id));
        if($response)
        {
            return "bongkar_log deleted successfully";
        }
        else
        {
            return "Error occuring while deleting bongkar_log";
        }
    }
}
