<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Cek_log_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get cek_log by id
     */
    function get_cek_log($id)
    {
        return $this->db->get_where('cek_log',array('id'=>$id))->row_array();
    }

    /*
     * Get all cek_log
     */
    function get_all_cek_log($no_bpk)
    {
      return $this->db->get_where('cek_log',array('bpk_no_bpk'=>$no_bpk))->result_array();
    }

    function get_total_cek_log($no_bpk)
    {
      return $this->db->get_where('v_total_cek_log',array('no_bpk'=>$no_bpk))->row_array();
    }

    /*
     * function to add new cek_log
     */
    function add_cek_log($params)
    {
        $this->db->insert('cek_log',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update cek_log
     */
    function update_cek_log($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('cek_log',$params);
        if($response)
        {
            return "cek_log updated successfully";
        }
        else
        {
            return "Error occuring while updating cek_log";
        }
    }

    function cek_log($no_bpk, $grade, $diameter)
    {
      if ($grade=='A' || $grade=='a') {
      $jml_count = $this->db->query("select a_rot,a_band1,a_band2,a_band3 from bongkar_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
      $count = $jml_count->row();
      $jumlah = $count->a_rot + $count->a_band1 + $count->a_band2 + $count->a_band3;

      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'a' => $jumlah,
              );
              $response = $this->db->update('cek_log',$params);
      }
      else if ($grade=='B' || $grade=='b') {
      $jml_count = $this->db->query("select b_rot,b_band1,b_band2,b_band3 from bongkar_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
      $count = $jml_count->row();
      $jumlah = $count->b_rot + $count->b_band1 + $count->b_band2 + $count->b_band3;

      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'b' => $jumlah,
              );
              $response = $this->db->update('cek_log',$params);
      }
      else if ($grade=='C' || $grade=='c') {
      $jml_count = $this->db->query("select c_rot,c_band1,c_band2,c_band3 from bongkar_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
      $count = $jml_count->row();
      $jumlah = $count->c_rot + $count->c_band1 + $count->c_band2 + $count->c_band3;

      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'c' => $jumlah,
              );
              $response = $this->db->update('cek_log',$params);
      }
      else if ($grade=='1M' || $grade=='1m') {
      $jml_count = $this->db->query("select satum_rot,satum_band1,satum_band2,satum_band3 from bongkar_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
      $count = $jml_count->row();
      $jumlah = $count->satum_rot + $count->satum_band1 + $count->satum_band2 + $count->satum_band3;

      $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
      $params = array(
                'satum' => $jumlah,
              );
              $response = $this->db->update('cek_log',$params);
      }
      else if ($grade=='AF' || $grade=='af') {
        $jml_count = $this->db->query("select afkir_rot,afkir_band1,afkir_band2,afkir_band3 from bongkar_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
        $count = $jml_count->row();
        $jumlah = $count->afkir_rot + $count->afkir_band1 + $count->afkir_band2 + $count->afkir_band3;

        $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
        $params = array(
                  'afkir' => $jumlah,
                );
                $response = $this->db->update('cek_log',$params);
      }
      // $response = $this->db->update('cek_log',$params);
    }

    /*
     * function to delete cek_log
     */
    function delete_cek_log($id)
    {
        $response = $this->db->delete('cek_log',array('id'=>$id));
        if($response)
        {
            return "cek_log deleted successfully";
        }
        else
        {
            return "Error occuring while deleting cek_log";
        }
    }
}
