<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Grade_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get grade by grade
     */
    function get_grade($grade)
    {
        return $this->db->get_where('grade',array('grade'=>$grade))->row_array();
    }
    
    /*
     * Get all grade
     */
    function get_all_grade()
    {
        return $this->db->get('grade')->result_array();
    }
    
    /*
     * function to add new grade
     */
    function add_grade($params)
    {
        $this->db->insert('grade',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update grade
     */
    function update_grade($grade,$params)
    {
        $this->db->where('grade',$grade);
        $response = $this->db->update('grade',$params);
        if($response)
        {
            return "grade updated successfully";
        }
        else
        {
            return "Error occuring while updating grade";
        }
    }
    
    /*
     * function to delete grade
     */
    function delete_grade($grade)
    {
        $response = $this->db->delete('grade',array('grade'=>$grade));
        if($response)
        {
            return "grade deleted successfully";
        }
        else
        {
            return "Error occuring while deleting grade";
        }
    }
}
