<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Harga_m3_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get harga_m3 by id
     */
    function get_harga_m3($id)
    {
        return $this->db->get_where('harga_m3',array('id'=>$id))->row_array();
    }

    /*
     * Get all harga_m3
     */
    function get_all_harga_m3()
    {
        $this->db->order_by('kode', 'asc');
        return $this->db->get('harga_m3')->result_array();
    }

    /*
     * function to add new harga_m3
     */
    function add_harga_m3($params)
    {
        $this->db->insert('harga_m3',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update harga_m3
     */
    function update_harga_m3($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('harga_m3',$params);
    }

    /*
     * function to delete harga_m3
     */
    function delete_harga_m3($id)
    {
        return $this->db->delete('harga_m3',array('id'=>$id));
    }
}
