<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Kubik_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get kubik by id
     */
    function get_kubik($id)
    {
        return $this->db->get_where('kubik',array('id'=>$id))->row_array();
    }

    /*
     * Get all kubik
     */
    function get_all_kubik()
    {
        $this->db->order_by('id', 'asc');
        return $this->db->get('kubik')->result_array();
    }

    /*
     * function to add new kubik
     */
    function add_kubik($params)
    {
        $this->db->insert('kubik',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update kubik
     */
    function update_kubik($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('kubik',$params);
    }

    /*
     * function to delete kubik
     */
    function delete_kubik($id)
    {
        return $this->db->delete('kubik',array('id'=>$id));
    }
}
