<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Log_rotary_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get log_rotary by id
     */
    function get_log_rotary($id)
    {
        return $this->db->get_where('log_rotary',array('id'=>$id))->row_array();
    }

    /*
     * Get all log_rotary
     */
    function get_all_log_rotary($id)
    {
        return $this->db->get_where('log_rotary',array('bpk_no_bpk'=>$id))->result_array();
    }

    /*
     * function to add new log_rotary
     */
    function add_log_rotary($params)
    {
        $this->db->insert('log_rotary',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update log_rotary
     */
    function update_log_rotary($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('log_rotary',$params);
        if($response)
        {
            return "log_rotary updated successfully";
        }
        else
        {
            return "Error occuring while updating log_rotary";
        }
    }

    /*
     * function to delete log_rotary
     */
    function delete_log_rotary($id)
    {
        $response = $this->db->delete('log_rotary',array('id'=>$id));
        if($response)
        {
            return "log_rotary deleted successfully";
        }
        else
        {
            return "Error occuring while deleting log_rotary";
        }
    }

    function get_number($id){
      $nomor = $this->db->get_where('log_rotary',array('bpk_no_bpk'=>$id));
      $no = $nomor->num_rows();
      return $no+1;
    }
}
