<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Rekap_total extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get rekap_pembayaran_log by id
     */
    function get_rekap_pembayaran_log($id)
    {
        return $this->db->get_where('rekap_pembayaran_log',array('bpk_no_bpk'=>$id))->result_array();
    }

    function format_angka($angka) {
      $hasil = number_format($angka,4,".",",");
      return $hasil;
    }

    function cetak_angka($angka) {
        $hasil = number_format($angka,4,",",".");
      	return $hasil;
    }

    function format_harga($angka) {
      $hasil = number_format($angka,0,",",".");
      return $hasil;
    }

    function get_ar($no_bpk){
      return $ar = $this->db->query("select sum(a_pc) as j_a_pc, sum(a_m3) as j_a_m3, sum(b_pc) as j_b_pc, sum(b_m3) as j_b_m3, sum(c_pc) as j_c_pc, sum(c_m3) as j_c_m3, sum(satum_pc) as j_satum_pc, sum(satum_m3) as j_satum_m3, sum(afkir_pc)  as j_afkir_pc, sum(afkir_m3) as j_afkir_m3 from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade between 6 and 8")->row_array();
    }
    function get_a0($no_bpk){
        return $a0 = $this->db->query("select sum(a_pc) as j_a_pc, sum(a_m3) as j_a_m3, sum(b_pc) as j_b_pc, sum(b_m3) as j_b_m3, sum(c_pc) as j_c_pc, sum(c_m3) as j_c_m3, sum(satum_pc) as j_satum_pc, sum(satum_m3) as j_satum_m3, sum(afkir_pc)  as j_afkir_pc, sum(afkir_m3) as j_afkir_m3 from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade between 9 and 14")->row_array();
    }
    function get_a1($no_bpk){
        return $a1 = $this->db->query("select sum(a_pc) as j_a_pc, sum(a_m3) as j_a_m3, sum(b_pc) as j_b_pc, sum(b_m3) as j_b_m3, sum(c_pc) as j_c_pc, sum(c_m3) as j_c_m3, sum(satum_pc) as j_satum_pc, sum(satum_m3) as j_satum_m3, sum(afkir_pc)  as j_afkir_pc, sum(afkir_m3) as j_afkir_m3 from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade between 15 and 19")->row_array();
    }
    function get_a21($no_bpk){
      return $a21 = $this->db->query("select sum(a_pc) as j_a_pc, sum(a_m3) as j_a_m3, sum(b_pc) as j_b_pc, sum(b_m3) as j_b_m3, sum(c_pc) as j_c_pc, sum(c_m3) as j_c_m3, sum(satum_pc) as j_satum_pc, sum(satum_m3) as j_satum_m3, sum(afkir_pc)  as j_afkir_pc, sum(afkir_m3) as j_afkir_m3 from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade between 20 and 24")->row_array();
    }
    function get_a22($no_bpk){
      return $a21 = $this->db->query("select sum(a_pc) as j_a_pc, sum(a_m3) as j_a_m3, sum(b_pc) as j_b_pc, sum(b_m3) as j_b_m3, sum(c_pc) as j_c_pc, sum(c_m3) as j_c_m3, sum(satum_pc) as j_satum_pc, sum(satum_m3) as j_satum_m3, sum(afkir_pc)  as j_afkir_pc, sum(afkir_m3) as j_afkir_m3 from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade between 25 and 29")->row_array();
    }
    function get_a3($no_bpk){
      return $a3 = $this->db->query("select sum(a_pc) as j_a_pc, sum(a_m3) as j_a_m3, sum(b_pc) as j_b_pc, sum(b_m3) as j_b_m3, sum(c_pc) as j_c_pc, sum(c_m3) as j_c_m3, sum(satum_pc) as j_satum_pc, sum(satum_m3) as j_satum_m3, sum(afkir_pc)  as j_afkir_pc, sum(afkir_m3) as j_afkir_m3 from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade between 30 and 39")->row_array();
    }
    function get_a4($no_bpk){
        return $a4 = $this->db->query("select sum(a_pc) as j_a_pc, sum(a_m3) as j_a_m3, sum(b_pc) as j_b_pc, sum(b_m3) as j_b_m3, sum(c_pc) as j_c_pc, sum(c_m3) as j_c_m3, sum(satum_pc) as j_satum_pc, sum(satum_m3) as j_satum_m3, sum(afkir_pc)  as j_afkir_pc, sum(afkir_m3) as j_afkir_m3 from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade >= 40")->row_array();
    }


}
