<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Selisih_stok_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get selisih_stok by id
     */
    function get_selisih_stok($id)
    {
        return $this->db->get_where('selisih_stok',array('id'=>$id))->row_array();
    }

    function cek_selisih_stok($no_bpk, $grade, $diameter)
    {
      if ($grade == 'A' || $grade == 'a') {
      $selisih = $this->db->get_where('selisih_stok',array('bpk_no_bpk'=>$no_bpk,'grade'=>$diameter))->row_array();
      return $selisih['a'];
      } else if ($grade == 'B' || $grade == 'b') {
      $selisih = $this->db->get_where('selisih_stok',array('bpk_no_bpk'=>$no_bpk,'grade'=>$diameter))->row_array();
      return $selisih['b'];
      } else if ($grade == 'C' || $grade == 'c') {
      $selisih = $this->db->get_where('selisih_stok',array('bpk_no_bpk'=>$no_bpk,'grade'=>$diameter))->row_array();
      return $selisih['c'];
    }else if ($grade == '1M' || $grade == '1m') {
      $selisih = $this->db->get_where('selisih_stok',array('bpk_no_bpk'=>$no_bpk,'grade'=>$diameter))->row_array();
      return $selisih['satum'];
    } else if ($grade == 'AF' || $grade == 'af') {
      $selisih = $this->db->get_where('selisih_stok',array('bpk_no_bpk'=>$no_bpk,'grade'=>$diameter))->row_array();
      return $selisih['afkir'];
    }

    }

    /*
     * Get all selisih_stok
     */
    function get_all_selisih_stok($no_bpk)
    {
        return $this->db->get_where('selisih_stok',array('bpk_no_bpk'=>$no_bpk))->result_array();
    }

    function get_total_selisih_stok($no_bpk)
    {
        return $this->db->get_where('v_total_selisih_stok',array('no_bpk'=>$no_bpk))->row_array();
    }

    /*
     * function to add new selisih_stok
     */
    function add_selisih_stok($params)
    {
        $this->db->insert('selisih_stok',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update selisih_stok
     */
    function update_selisih_stok($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('selisih_stok',$params);
        if($response)
        {
            return "selisih_stok updated successfully";
        }
        else
        {
            return "Error occuring while updating selisih_stok";
        }
    }

    function selisih_stok($no_bpk, $grade, $diameter)
    {
      if ($grade == 'A' || $grade == 'a') {
          $jml_rekap_log = $this->db->query("select a_pc from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
          $pc = $jml_rekap_log->row();

          $jml_cek_log = $this->db->query("select a from cek_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
          $cek_log = $jml_cek_log->row();

          $selisih = $pc->a_pc - $cek_log->a;

          $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
          $params = array(
                    'a' => $selisih,
                  );
                  $response = $this->db->update('selisih_stok',$params);

      }
      else if ($grade == 'B' || $grade == 'b') {
          $jml_rekap_log = $this->db->query("select b_pc from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
          $pc = $jml_rekap_log->row();

          $jml_cek_log = $this->db->query("select b from cek_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
          $cek_log = $jml_cek_log->row();

          $selisih = $pc->b_pc - $cek_log->b;

          $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
          $params = array(
                    'b' => $selisih,
                  );
                  $response = $this->db->update('selisih_stok',$params);

      }
      else if ($grade == 'C' || $grade == 'c') {
          $jml_rekap_log = $this->db->query("select c_pc from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
          $pc = $jml_rekap_log->row();

          $jml_cek_log = $this->db->query("select c from cek_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
          $cek_log = $jml_cek_log->row();

          $selisih = $pc->c_pc - $cek_log->c;

          $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
          $params = array(
                    'c' => $selisih,
                  );
                  $response = $this->db->update('selisih_stok',$params);

      }
      else if ($grade == '1M' || $grade == '1m') {
          $jml_rekap_log = $this->db->query("select satum_pc from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
          $pc = $jml_rekap_log->row();

          $jml_cek_log = $this->db->query("select satum from cek_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
          $cek_log = $jml_cek_log->row();

          $selisih = $pc->satum_pc - $cek_log->satum;

          $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
          $params = array(
                    'satum' => $selisih,
                  );
                  $response = $this->db->update('selisih_stok',$params);

      }
      else if ($grade == 'AF' || $grade == 'af' || $grade == 'Af') {
          $jml_rekap_log = $this->db->query("select afkir_pc from rekap_pembayaran_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
          $pc = $jml_rekap_log->row();

          $jml_cek_log = $this->db->query("select afkir from cek_log where bpk_no_bpk='$no_bpk' and grade='$diameter'");
          $cek_log = $jml_cek_log->row();

          $selisih = $pc->afkir_pc - $cek_log->afkir;

          $this->db->where(array('grade'=>$diameter,'bpk_no_bpk'=>$no_bpk));
          $params = array(
                    'afkir' => $selisih,
                  );
                  $response = $this->db->update('selisih_stok',$params);

      }
    }
    /*
     * function to delete selisih_stok
     */
    function delete_selisih_stok($id)
    {
        $response = $this->db->delete('selisih_stok',array('id'=>$id));
        if($response)
        {
            return "selisih_stok deleted successfully";
        }
        else
        {
            return "Error occuring while deleting selisih_stok";
        }
    }
}
