<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Bansaw1 extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bpk_model');
        $this->load->model('Bansaw1_model');
        $this->load->model('Bongkar_log_model');
        $this->load->model('Cek_log_model');
        $this->load->model('Selisih_stok_model');
    }

    /*
     * Listing of bansaw1
     */
    function index()
    {
        $data['bansaw1'] = $this->Bansaw1_model->get_all_bansaw1($this->session->userdata('no_bpk'));
        $data['cek_log'] = $this->Cek_log_model->get_all_cek_log($this->session->userdata('no_bpk'));
        $data['total_cek_log'] = $this->Cek_log_model->get_total_cek_log($this->session->userdata('no_bpk'));
        $data['selisih_stok'] = $this->Selisih_stok_model->get_all_selisih_stok($this->session->userdata('no_bpk'));
        $data['total_selisih_stok'] = $this->Selisih_stok_model->get_total_selisih_stok($this->session->userdata('no_bpk'));

        $data['_view'] = 'bansaw1/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bansaw1
     */
    function add()
    {
      $data['bansaw1'] = $this->Bansaw1_model->get_all_bansaw1($this->session->userdata('no_bpk'));

        $this->load->library('form_validation');

		$this->form_validation->set_rules('no','No','required|integer');
		$this->form_validation->set_rules('diameter','Diameter','required|integer');
		$this->form_validation->set_rules('grade_grade','Grade Grade','max_length[5]');

		if($this->form_validation->run())
        {
            $params = array(
				'no' => $this->input->post('no'),
				'diameter' => $this->input->post('diameter'),
				'tanggal' => $this->Bpk_model->InggrisTgl($this->input->post('tanggal')),
        'grade_grade' => $this->input->post('grade_grade'),
        'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
            );

            $selisih = $this->Selisih_stok_model->cek_selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

            if ($selisih>=1) {
            $bansaw1_id = $this->Bansaw1_model->add_bansaw1($params);
            $this->Bongkar_log_model->bongkar_log_bansaw1($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);
            $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);
            $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);
            redirect('bansaw1/add');
            } else {
              $data['gagal'] = 'stok yang anda masukkan sudah tidak ada !! ulangi perintah';
              $data['_view'] = 'bansaw1/add';
              $this->load->view('layouts/main',$data);
            }

        }
        else
        {
            $data['_view'] = 'bansaw1/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a bansaw1
     */
    function edit($id)
    {
        // check if the bansaw1 exists before trying to edit it
        $data['bansaw1'] = $this->Bansaw1_model->get_bansaw1($id);

        if(isset($data['bansaw1']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('no','No','required|integer');
			$this->form_validation->set_rules('diameter','Diameter','required|integer');
			$this->form_validation->set_rules('grade_grade','Grade Grade','max_length[5]');

			if($this->form_validation->run())
            {
                $params = array(
					'no' => $this->input->post('no'),
					'diameter' => $this->input->post('diameter'),
          'tanggal' => $this->Bpk_model->InggrisTgl($this->input->post('tanggal')),
          'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
					'grade_grade' => $this->input->post('grade_grade'),
                );

                $this->Bansaw1_model->update_bansaw1($id,$params);
                $this->Bongkar_log_model->bongkar_log_bansaw1($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Bongkar_log_model->bongkar_log_bansaw1($params['bpk_no_bpk'],$data['bansaw1']['grade_grade'],$data['bansaw1']['diameter']);

                $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$data['bansaw1']['grade_grade'],$data['bansaw1']['diameter']);

                $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$data['bansaw1']['grade_grade'],$data['bansaw1']['diameter']);
                redirect('bansaw1/index');
            }
            else
            {
                $data['_view'] = 'bansaw1/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bansaw1 you are trying to edit does not exist.');
    }

    /*
     * Deleting bansaw1
     */
    function remove($id)
    {
        $bansaw1 = $this->Bansaw1_model->get_bansaw1($id);

        // check if the bansaw1 exists before trying to delete it
        if(isset($bansaw1['id']))
        {
            $this->Bansaw1_model->delete_bansaw1($id);
            $this->Bongkar_log_model->bongkar_log_bansaw1($bansaw1['bpk_no_bpk'],$bansaw1['grade_grade'],$bansaw1['diameter']);

            $this->Cek_log_model->cek_log($bansaw1['bpk_no_bpk'],$bansaw1['grade_grade'],$bansaw1['diameter']);

            $this->Selisih_stok_model->selisih_stok($bansaw1['bpk_no_bpk'],$bansaw1['grade_grade'],$bansaw1['diameter']);

            redirect('bansaw1/index');
        }
        else
            show_error('The bansaw1 you are trying to delete does not exist.');
    }

    function removeall($bpk)
    {
            $bansaw1 = $this->Bansaw1_model->get_all_bansaw1($bpk);

            foreach ($bansaw1 as $r) {
              $this->Bansaw1_model->delete_bansaw1($r['id']);
              $this->Bongkar_log_model->bongkar_log_bansaw1($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
              $this->Cek_log_model->cek_log($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
              $this->Selisih_stok_model->selisih_stok($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
            }


            redirect('bansaw1/index');
    }

}
