<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Bansaw3 extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bansaw3_model');
        $this->load->model('Bpk_model');
        $this->load->model('Bongkar_log_model');
        $this->load->model('Cek_log_model');
        $this->load->model('Selisih_stok_model');
    }

    /*
     * Listing of bansaw3
     */
    function index()
    {
      $data['bansaw3'] = $this->Bansaw3_model->get_all_bansaw3($this->session->userdata('no_bpk'));
      $data['cek_log'] = $this->Cek_log_model->get_all_cek_log($this->session->userdata('no_bpk'));
      $data['total_cek_log'] = $this->Cek_log_model->get_total_cek_log($this->session->userdata('no_bpk'));
      $data['selisih_stok'] = $this->Selisih_stok_model->get_all_selisih_stok($this->session->userdata('no_bpk'));
      $data['total_selisih_stok'] = $this->Selisih_stok_model->get_total_selisih_stok($this->session->userdata('no_bpk'));
        $data['_view'] = 'bansaw3/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bansaw3
     */
    function add()
    {
      $data['bansaw3'] = $this->Bansaw3_model->get_all_bansaw3($this->session->userdata('no_bpk'));

        $this->load->library('form_validation');

		$this->form_validation->set_rules('no','No','required|integer');
		$this->form_validation->set_rules('diameter','Diameter','required|integer');
		$this->form_validation->set_rules('grade_grade','Grade Grade','max_length[5]');

		if($this->form_validation->run())
        {
            $params = array(
				'no' => $this->input->post('no'),
				'diameter' => $this->input->post('diameter'),
				'tanggal' => $this->Bpk_model->InggrisTgl($this->input->post('tanggal')),
				'grade_grade' => $this->input->post('grade_grade'),
        'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
            );

            $selisih = $this->Selisih_stok_model->cek_selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

            if ($selisih>=1) {
            $bansaw3_id = $this->Bansaw3_model->add_bansaw3($params);
            $this->Bongkar_log_model->bongkar_log_bansaw3($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);
            $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);
            $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);
            redirect('bansaw3/add');
            } else {
              $data['gagal'] = 'stok yang anda masukkan sudah tidak ada !! ulangi perintah';
              $data['_view'] = 'bansaw3/add';
              $this->load->view('layouts/main',$data);
            }
        }
        else
        {
            $data['_view'] = 'bansaw3/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a bansaw3
     */
    function edit($id)
    {
        // check if the bansaw3 exists before trying to edit it
        $data['bansaw3'] = $this->Bansaw3_model->get_bansaw3($id);

        if(isset($data['bansaw3']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('no','No','required|integer');
			$this->form_validation->set_rules('diameter','Diameter','required|integer');
			$this->form_validation->set_rules('grade_grade','Grade Grade','max_length[5]');

			if($this->form_validation->run())
            {
                $params = array(
					'no' => $this->input->post('no'),
					'diameter' => $this->input->post('diameter'),
          'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
          'tanggal' => $this->Bpk_model->InggrisTgl($this->input->post('tanggal')),
					'grade_grade' => $this->input->post('grade_grade'),
                );

                $this->Bansaw3_model->update_bansaw3($id,$params);
                $this->Bongkar_log_model->bongkar_log_bansaw3($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Bongkar_log_model->bongkar_log_bansaw3($params['bpk_no_bpk'],$data['bansaw3']['grade_grade'],$data['bansaw3']['diameter']);

                $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$data['bansaw3']['grade_grade'],$data['bansaw3']['diameter']);

                $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$data['bansaw3']['grade_grade'],$data['bansaw3']['diameter']);

                redirect('bansaw3/index');
            }
            else
            {
                $data['_view'] = 'bansaw3/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bansaw3 you are trying to edit does not exist.');
    }

    /*
     * Deleting bansaw3
     */
    function remove($id)
    {
        $bansaw3 = $this->Bansaw3_model->get_bansaw3($id);

        // check if the bansaw3 exists before trying to delete it
        if(isset($bansaw3['id']))
        {
            $this->Bansaw3_model->delete_bansaw3($id);
            $this->Bongkar_log_model->bongkar_log_bansaw3($bansaw3['bpk_no_bpk'],$bansaw3['grade_grade'],$bansaw3['diameter']);

            $this->Cek_log_model->cek_log($bansaw3['bpk_no_bpk'],$bansaw3['grade_grade'],$bansaw3['diameter']);

            $this->Selisih_stok_model->selisih_stok($bansaw3['bpk_no_bpk'],$bansaw3['grade_grade'],$bansaw3['diameter']);

            redirect('bansaw3/index');
        }
        else
            show_error('The bansaw3 you are trying to delete does not exist.');
    }

    function removeall($bpk)
    {
            $bansaw3 = $this->Bansaw3_model->get_all_bansaw3($bpk);

            foreach ($bansaw3 as $r) {
              $this->Bansaw3_model->delete_bansaw3($r['id']);
              $this->Bongkar_log_model->bongkar_log_bansaw3($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
              $this->Cek_log_model->cek_log($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
              $this->Selisih_stok_model->selisih_stok($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
            }


            redirect('bansaw3/index');
    }
}
