<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Bansaw2 extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bpk_model');
        $this->load->model('Bansaw2_model');
        $this->load->model('Bongkar_log_model');
        $this->load->model('Cek_log_model');
        $this->load->model('Selisih_stok_model');
    }

    /*
     * Listing of bansaw2
     */
    function index()
    {

      $data['bansaw2'] = $this->Bansaw2_model->get_all_bansaw2($this->session->userdata('no_bpk'));
      $data['cek_log'] = $this->Cek_log_model->get_all_cek_log($this->session->userdata('no_bpk'));
      $data['total_cek_log'] = $this->Cek_log_model->get_total_cek_log($this->session->userdata('no_bpk'));
      $data['selisih_stok'] = $this->Selisih_stok_model->get_all_selisih_stok($this->session->userdata('no_bpk'));
      $data['total_selisih_stok'] = $this->Selisih_stok_model->get_total_selisih_stok($this->session->userdata('no_bpk'));

        $data['_view'] = 'bansaw2/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bansaw2
     */
    function add()
    {
      $data['bansaw2'] = $this->Bansaw2_model->get_all_bansaw2($this->session->userdata('no_bpk'));

        $this->load->library('form_validation');

		$this->form_validation->set_rules('no','No','required|integer');
		$this->form_validation->set_rules('diameter','Diameter','required|integer');
		$this->form_validation->set_rules('grade_grade','Grade Grade','max_length[5]');

		if($this->form_validation->run())
        {
            $params = array(
				'no' => $this->input->post('no'),
				'diameter' => $this->input->post('diameter'),
				'tanggal' => $this->Bpk_model->InggrisTgl($this->input->post('tanggal')),
				'grade_grade' => $this->input->post('grade_grade'),
        'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
            );

            $selisih = $this->Selisih_stok_model->cek_selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

            if ($selisih>=1) {
            $bansaw2_id = $this->Bansaw2_model->add_bansaw2($params);
            $this->Bongkar_log_model->bongkar_log_bansaw2($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);
            $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);
            $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);
            redirect('bansaw2/add');
            } else {
              $data['gagal'] = 'stok yang anda masukkan sudah tidak ada !! ulangi perintah';
              $data['_view'] = 'bansaw2/add';
              $this->load->view('layouts/main',$data);
            }
        }
        else
        {
            $data['_view'] = 'bansaw2/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a bansaw2
     */
    function edit($id)
    {
        // check if the bansaw2 exists before trying to edit it
        $data['bansaw2'] = $this->Bansaw2_model->get_bansaw2($id);

        if(isset($data['bansaw2']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('no','No','required|integer');
			$this->form_validation->set_rules('diameter','Diameter','required|integer');
			$this->form_validation->set_rules('grade_grade','Grade Grade','max_length[5]');

			if($this->form_validation->run())
            {
                $params = array(
					'no' => $this->input->post('no'),
					'diameter' => $this->input->post('diameter'),
          'tanggal' => $this->Bpk_model->InggrisTgl($this->input->post('tanggal')),
          'bpk_no_bpk' => $this->input->post('bpk_no_bpk'),
					'grade_grade' => $this->input->post('grade_grade'),
                );

                $this->Bansaw2_model->update_bansaw2($id,$params);

                $this->Bongkar_log_model->bongkar_log_bansaw2($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$params['grade_grade'],$params['diameter']);

                $this->Bongkar_log_model->bongkar_log_bansaw2($params['bpk_no_bpk'],$data['bansaw2']['grade_grade'],$data['bansaw2']['diameter']);

                $this->Cek_log_model->cek_log($params['bpk_no_bpk'],$data['bansaw2']['grade_grade'],$data['bansaw2']['diameter']);

                $this->Selisih_stok_model->selisih_stok($params['bpk_no_bpk'],$data['bansaw2']['grade_grade'],$data['bansaw2']['diameter']);

                redirect('bansaw2/index');
            }
            else
            {
                $data['_view'] = 'bansaw2/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bansaw2 you are trying to edit does not exist.');
    }

    /*
     * Deleting bansaw2
     */
    function remove($id)
    {
        $bansaw2 = $this->Bansaw2_model->get_bansaw2($id);

        // check if the bansaw2 exists before trying to delete it
        if(isset($bansaw2['id']))
        {
            $this->Bansaw2_model->delete_bansaw2($id);
            $this->Bongkar_log_model->bongkar_log_bansaw2($bansaw2['bpk_no_bpk'],$bansaw2['grade_grade'],$bansaw2['diameter']);

            $this->Cek_log_model->cek_log($bansaw2['bpk_no_bpk'],$bansaw2['grade_grade'],$bansaw2['diameter']);

            $this->Selisih_stok_model->selisih_stok($bansaw2['bpk_no_bpk'],$bansaw2['grade_grade'],$bansaw2['diameter']);

            redirect('bansaw2/index');
        }
        else
            show_error('The bansaw2 you are trying to delete does not exist.');
    }

    function removeall($bpk)
    {
            $bansaw2 = $this->Bansaw2_model->get_all_bansaw2($bpk);

            foreach ($bansaw2 as $r) {
              $this->Bansaw2_model->delete_bansaw2($r['id']);
              $this->Bongkar_log_model->bongkar_log_bansaw2($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
              $this->Cek_log_model->cek_log($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
              $this->Selisih_stok_model->selisih_stok($r['bpk_no_bpk'],$r['grade_grade'],$r['diameter']);
            }


            redirect('bansaw2/index');
    }

}
